# $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilnesserr
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - zerologlint
  settings:
    funlen:
      lines: 100
      statements: 80
    goconst:
      min-len: 6
      min-occurrences: 50
    revive:
      rules:
        - name: file-length-limit
          arguments:
            - max: 300
              skip-comments: true
              skip-blank-lines: true
  exclusions:
    paths:
      - ".*_gen\\.go$"
formatters:
  enable:
    - gofmt
