// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AnalyticsRealtimeDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"active_users": schema.StringAttribute{
				Computed: true,
			},
			"events_per_minute": schema.StringAttribute{
				Computed: true,
			},
			"recent_events": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"content_id": schema.StringAttribute{
							Computed: true,
						},
						"event_type": schema.StringAttribute{
							Computed: true,
						},
						"timestamp": schema.StringAttribute{
							Computed: true,
						},
						"user_id": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: AnalyticsRealtimeRecentEventsType{
						ObjectType: types.ObjectType{
							AttrTypes: AnalyticsRealtimeRecentEventsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"timestamp": schema.StringAttribute{
				Computed: true,
			},
			"top_countries": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"count": schema.StringAttribute{
							Computed: true,
						},
						"country": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: AnalyticsRealtimeTopCountriesType{
						ObjectType: types.ObjectType{
							AttrTypes: AnalyticsRealtimeTopCountriesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"top_events": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"count": schema.StringAttribute{
							Computed: true,
						},
						"event_type": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: AnalyticsRealtimeTopEventsType{
						ObjectType: types.ObjectType{
							AttrTypes: AnalyticsRealtimeTopEventsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type AnalyticsRealtimeModel struct {
	ActiveUsers     types.String `tfsdk:"active_users"`
	EventsPerMinute types.String `tfsdk:"events_per_minute"`
	RecentEvents    types.List   `tfsdk:"recent_events"`
	Timestamp       types.String `tfsdk:"timestamp"`
	TopCountries    types.List   `tfsdk:"top_countries"`
	TopEvents       types.List   `tfsdk:"top_events"`
}

var _ basetypes.ObjectTypable = AnalyticsRealtimeRecentEventsType{}

type AnalyticsRealtimeRecentEventsType struct {
	basetypes.ObjectType
}

func (t AnalyticsRealtimeRecentEventsType) Equal(o attr.Type) bool {
	other, ok := o.(AnalyticsRealtimeRecentEventsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AnalyticsRealtimeRecentEventsType) String() string {
	return "AnalyticsRealtimeRecentEventsType"
}

func (t AnalyticsRealtimeRecentEventsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	contentIdAttribute, ok := attributes["content_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`content_id is missing from object`)

		return nil, diags
	}

	contentIdVal, ok := contentIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`content_id expected to be basetypes.StringValue, was: %T`, contentIdAttribute))
	}

	eventTypeAttribute, ok := attributes["event_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`event_type is missing from object`)

		return nil, diags
	}

	eventTypeVal, ok := eventTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`event_type expected to be basetypes.StringValue, was: %T`, eventTypeAttribute))
	}

	timestampAttribute, ok := attributes["timestamp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`timestamp is missing from object`)

		return nil, diags
	}

	timestampVal, ok := timestampAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`timestamp expected to be basetypes.StringValue, was: %T`, timestampAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return nil, diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AnalyticsRealtimeRecentEventsValue{
		ContentId: contentIdVal,
		EventType: eventTypeVal,
		Timestamp: timestampVal,
		UserId:    userIdVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func AnalyticsRealtimeNewRecentEventsValueNull() AnalyticsRealtimeRecentEventsValue {
	return AnalyticsRealtimeRecentEventsValue{
		state: attr.ValueStateNull,
	}
}

func AnalyticsRealtimeNewRecentEventsValueUnknown() AnalyticsRealtimeRecentEventsValue {
	return AnalyticsRealtimeRecentEventsValue{
		state: attr.ValueStateUnknown,
	}
}

func AnalyticsRealtimeNewRecentEventsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AnalyticsRealtimeRecentEventsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AnalyticsRealtimeRecentEventsValue Attribute Value",
				"While creating a AnalyticsRealtimeRecentEventsValue value, a missing attribute value was detected. "+
					"A AnalyticsRealtimeRecentEventsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AnalyticsRealtimeRecentEventsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AnalyticsRealtimeRecentEventsValue Attribute Type",
				"While creating a AnalyticsRealtimeRecentEventsValue value, an invalid attribute value was detected. "+
					"A AnalyticsRealtimeRecentEventsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AnalyticsRealtimeRecentEventsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AnalyticsRealtimeRecentEventsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AnalyticsRealtimeRecentEventsValue Attribute Value",
				"While creating a AnalyticsRealtimeRecentEventsValue value, an extra attribute value was detected. "+
					"A AnalyticsRealtimeRecentEventsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AnalyticsRealtimeRecentEventsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return AnalyticsRealtimeNewRecentEventsValueUnknown(), diags
	}

	contentIdAttribute, ok := attributes["content_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`content_id is missing from object`)

		return AnalyticsRealtimeNewRecentEventsValueUnknown(), diags
	}

	contentIdVal, ok := contentIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`content_id expected to be basetypes.StringValue, was: %T`, contentIdAttribute))
	}

	eventTypeAttribute, ok := attributes["event_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`event_type is missing from object`)

		return AnalyticsRealtimeNewRecentEventsValueUnknown(), diags
	}

	eventTypeVal, ok := eventTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`event_type expected to be basetypes.StringValue, was: %T`, eventTypeAttribute))
	}

	timestampAttribute, ok := attributes["timestamp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`timestamp is missing from object`)

		return AnalyticsRealtimeNewRecentEventsValueUnknown(), diags
	}

	timestampVal, ok := timestampAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`timestamp expected to be basetypes.StringValue, was: %T`, timestampAttribute))
	}

	userIdAttribute, ok := attributes["user_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`user_id is missing from object`)

		return AnalyticsRealtimeNewRecentEventsValueUnknown(), diags
	}

	userIdVal, ok := userIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`user_id expected to be basetypes.StringValue, was: %T`, userIdAttribute))
	}

	if diags.HasError() {
		return AnalyticsRealtimeNewRecentEventsValueUnknown(), diags
	}

	return AnalyticsRealtimeRecentEventsValue{
		ContentId: contentIdVal,
		EventType: eventTypeVal,
		Timestamp: timestampVal,
		UserId:    userIdVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func AnalyticsRealtimeNewRecentEventsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AnalyticsRealtimeRecentEventsValue {
	object, diags := AnalyticsRealtimeNewRecentEventsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("AnalyticsRealtimeNewRecentEventsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AnalyticsRealtimeRecentEventsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return AnalyticsRealtimeNewRecentEventsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return AnalyticsRealtimeNewRecentEventsValueUnknown(), nil
	}

	if in.IsNull() {
		return AnalyticsRealtimeNewRecentEventsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return AnalyticsRealtimeNewRecentEventsValueMust(AnalyticsRealtimeRecentEventsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AnalyticsRealtimeRecentEventsType) ValueType(ctx context.Context) attr.Value {
	return AnalyticsRealtimeRecentEventsValue{}
}

var _ basetypes.ObjectValuable = AnalyticsRealtimeRecentEventsValue{}

type AnalyticsRealtimeRecentEventsValue struct {
	ContentId basetypes.StringValue `tfsdk:"content_id"`
	EventType basetypes.StringValue `tfsdk:"event_type"`
	Timestamp basetypes.StringValue `tfsdk:"timestamp"`
	UserId    basetypes.StringValue `tfsdk:"user_id"`
	state     attr.ValueState
}

func (v AnalyticsRealtimeRecentEventsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["content_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["event_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["timestamp"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["user_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.ContentId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["content_id"] = val

		val, err = v.EventType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["event_type"] = val

		val, err = v.Timestamp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["timestamp"] = val

		val, err = v.UserId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["user_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AnalyticsRealtimeRecentEventsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AnalyticsRealtimeRecentEventsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AnalyticsRealtimeRecentEventsValue) String() string {
	return "AnalyticsRealtimeRecentEventsValue"
}

func (v AnalyticsRealtimeRecentEventsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"content_id": basetypes.StringType{},
		"event_type": basetypes.StringType{},
		"timestamp":  basetypes.StringType{},
		"user_id":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"content_id": v.ContentId,
			"event_type": v.EventType,
			"timestamp":  v.Timestamp,
			"user_id":    v.UserId,
		})

	return objVal, diags
}

func (v AnalyticsRealtimeRecentEventsValue) Equal(o attr.Value) bool {
	other, ok := o.(AnalyticsRealtimeRecentEventsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ContentId.Equal(other.ContentId) {
		return false
	}

	if !v.EventType.Equal(other.EventType) {
		return false
	}

	if !v.Timestamp.Equal(other.Timestamp) {
		return false
	}

	if !v.UserId.Equal(other.UserId) {
		return false
	}

	return true
}

func (v AnalyticsRealtimeRecentEventsValue) Type(ctx context.Context) attr.Type {
	return AnalyticsRealtimeRecentEventsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AnalyticsRealtimeRecentEventsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"content_id": basetypes.StringType{},
		"event_type": basetypes.StringType{},
		"timestamp":  basetypes.StringType{},
		"user_id":    basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = AnalyticsRealtimeTopCountriesType{}

type AnalyticsRealtimeTopCountriesType struct {
	basetypes.ObjectType
}

func (t AnalyticsRealtimeTopCountriesType) Equal(o attr.Type) bool {
	other, ok := o.(AnalyticsRealtimeTopCountriesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AnalyticsRealtimeTopCountriesType) String() string {
	return "AnalyticsRealtimeTopCountriesType"
}

func (t AnalyticsRealtimeTopCountriesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	countAttribute, ok := attributes["count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`count is missing from object`)

		return nil, diags
	}

	countVal, ok := countAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`count expected to be basetypes.StringValue, was: %T`, countAttribute))
	}

	countryAttribute, ok := attributes["country"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`country is missing from object`)

		return nil, diags
	}

	countryVal, ok := countryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`country expected to be basetypes.StringValue, was: %T`, countryAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AnalyticsRealtimeTopCountriesValue{
		Count:   countVal,
		Country: countryVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func AnalyticsRealtimeNewTopCountriesValueNull() AnalyticsRealtimeTopCountriesValue {
	return AnalyticsRealtimeTopCountriesValue{
		state: attr.ValueStateNull,
	}
}

func AnalyticsRealtimeNewTopCountriesValueUnknown() AnalyticsRealtimeTopCountriesValue {
	return AnalyticsRealtimeTopCountriesValue{
		state: attr.ValueStateUnknown,
	}
}

func AnalyticsRealtimeNewTopCountriesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AnalyticsRealtimeTopCountriesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AnalyticsRealtimeTopCountriesValue Attribute Value",
				"While creating a AnalyticsRealtimeTopCountriesValue value, a missing attribute value was detected. "+
					"A AnalyticsRealtimeTopCountriesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AnalyticsRealtimeTopCountriesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AnalyticsRealtimeTopCountriesValue Attribute Type",
				"While creating a AnalyticsRealtimeTopCountriesValue value, an invalid attribute value was detected. "+
					"A AnalyticsRealtimeTopCountriesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AnalyticsRealtimeTopCountriesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AnalyticsRealtimeTopCountriesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AnalyticsRealtimeTopCountriesValue Attribute Value",
				"While creating a AnalyticsRealtimeTopCountriesValue value, an extra attribute value was detected. "+
					"A AnalyticsRealtimeTopCountriesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AnalyticsRealtimeTopCountriesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return AnalyticsRealtimeNewTopCountriesValueUnknown(), diags
	}

	countAttribute, ok := attributes["count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`count is missing from object`)

		return AnalyticsRealtimeNewTopCountriesValueUnknown(), diags
	}

	countVal, ok := countAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`count expected to be basetypes.StringValue, was: %T`, countAttribute))
	}

	countryAttribute, ok := attributes["country"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`country is missing from object`)

		return AnalyticsRealtimeNewTopCountriesValueUnknown(), diags
	}

	countryVal, ok := countryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`country expected to be basetypes.StringValue, was: %T`, countryAttribute))
	}

	if diags.HasError() {
		return AnalyticsRealtimeNewTopCountriesValueUnknown(), diags
	}

	return AnalyticsRealtimeTopCountriesValue{
		Count:   countVal,
		Country: countryVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func AnalyticsRealtimeNewTopCountriesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AnalyticsRealtimeTopCountriesValue {
	object, diags := AnalyticsRealtimeNewTopCountriesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("AnalyticsRealtimeNewTopCountriesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AnalyticsRealtimeTopCountriesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return AnalyticsRealtimeNewTopCountriesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return AnalyticsRealtimeNewTopCountriesValueUnknown(), nil
	}

	if in.IsNull() {
		return AnalyticsRealtimeNewTopCountriesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return AnalyticsRealtimeNewTopCountriesValueMust(AnalyticsRealtimeTopCountriesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AnalyticsRealtimeTopCountriesType) ValueType(ctx context.Context) attr.Value {
	return AnalyticsRealtimeTopCountriesValue{}
}

var _ basetypes.ObjectValuable = AnalyticsRealtimeTopCountriesValue{}

type AnalyticsRealtimeTopCountriesValue struct {
	Count   basetypes.StringValue `tfsdk:"count"`
	Country basetypes.StringValue `tfsdk:"country"`
	state   attr.ValueState
}

func (v AnalyticsRealtimeTopCountriesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["count"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["country"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Count.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["count"] = val

		val, err = v.Country.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["country"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AnalyticsRealtimeTopCountriesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AnalyticsRealtimeTopCountriesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AnalyticsRealtimeTopCountriesValue) String() string {
	return "AnalyticsRealtimeTopCountriesValue"
}

func (v AnalyticsRealtimeTopCountriesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"count":   basetypes.StringType{},
		"country": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"count":   v.Count,
			"country": v.Country,
		})

	return objVal, diags
}

func (v AnalyticsRealtimeTopCountriesValue) Equal(o attr.Value) bool {
	other, ok := o.(AnalyticsRealtimeTopCountriesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Count.Equal(other.Count) {
		return false
	}

	if !v.Country.Equal(other.Country) {
		return false
	}

	return true
}

func (v AnalyticsRealtimeTopCountriesValue) Type(ctx context.Context) attr.Type {
	return AnalyticsRealtimeTopCountriesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AnalyticsRealtimeTopCountriesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"count":   basetypes.StringType{},
		"country": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = AnalyticsRealtimeTopEventsType{}

type AnalyticsRealtimeTopEventsType struct {
	basetypes.ObjectType
}

func (t AnalyticsRealtimeTopEventsType) Equal(o attr.Type) bool {
	other, ok := o.(AnalyticsRealtimeTopEventsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AnalyticsRealtimeTopEventsType) String() string {
	return "AnalyticsRealtimeTopEventsType"
}

func (t AnalyticsRealtimeTopEventsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	countAttribute, ok := attributes["count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`count is missing from object`)

		return nil, diags
	}

	countVal, ok := countAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`count expected to be basetypes.StringValue, was: %T`, countAttribute))
	}

	eventTypeAttribute, ok := attributes["event_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`event_type is missing from object`)

		return nil, diags
	}

	eventTypeVal, ok := eventTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`event_type expected to be basetypes.StringValue, was: %T`, eventTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AnalyticsRealtimeTopEventsValue{
		Count:     countVal,
		EventType: eventTypeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func AnalyticsRealtimeNewTopEventsValueNull() AnalyticsRealtimeTopEventsValue {
	return AnalyticsRealtimeTopEventsValue{
		state: attr.ValueStateNull,
	}
}

func AnalyticsRealtimeNewTopEventsValueUnknown() AnalyticsRealtimeTopEventsValue {
	return AnalyticsRealtimeTopEventsValue{
		state: attr.ValueStateUnknown,
	}
}

func AnalyticsRealtimeNewTopEventsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AnalyticsRealtimeTopEventsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AnalyticsRealtimeTopEventsValue Attribute Value",
				"While creating a AnalyticsRealtimeTopEventsValue value, a missing attribute value was detected. "+
					"A AnalyticsRealtimeTopEventsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AnalyticsRealtimeTopEventsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AnalyticsRealtimeTopEventsValue Attribute Type",
				"While creating a AnalyticsRealtimeTopEventsValue value, an invalid attribute value was detected. "+
					"A AnalyticsRealtimeTopEventsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AnalyticsRealtimeTopEventsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AnalyticsRealtimeTopEventsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AnalyticsRealtimeTopEventsValue Attribute Value",
				"While creating a AnalyticsRealtimeTopEventsValue value, an extra attribute value was detected. "+
					"A AnalyticsRealtimeTopEventsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AnalyticsRealtimeTopEventsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return AnalyticsRealtimeNewTopEventsValueUnknown(), diags
	}

	countAttribute, ok := attributes["count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`count is missing from object`)

		return AnalyticsRealtimeNewTopEventsValueUnknown(), diags
	}

	countVal, ok := countAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`count expected to be basetypes.StringValue, was: %T`, countAttribute))
	}

	eventTypeAttribute, ok := attributes["event_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`event_type is missing from object`)

		return AnalyticsRealtimeNewTopEventsValueUnknown(), diags
	}

	eventTypeVal, ok := eventTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`event_type expected to be basetypes.StringValue, was: %T`, eventTypeAttribute))
	}

	if diags.HasError() {
		return AnalyticsRealtimeNewTopEventsValueUnknown(), diags
	}

	return AnalyticsRealtimeTopEventsValue{
		Count:     countVal,
		EventType: eventTypeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func AnalyticsRealtimeNewTopEventsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AnalyticsRealtimeTopEventsValue {
	object, diags := AnalyticsRealtimeNewTopEventsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("AnalyticsRealtimeNewTopEventsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AnalyticsRealtimeTopEventsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return AnalyticsRealtimeNewTopEventsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return AnalyticsRealtimeNewTopEventsValueUnknown(), nil
	}

	if in.IsNull() {
		return AnalyticsRealtimeNewTopEventsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return AnalyticsRealtimeNewTopEventsValueMust(AnalyticsRealtimeTopEventsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AnalyticsRealtimeTopEventsType) ValueType(ctx context.Context) attr.Value {
	return AnalyticsRealtimeTopEventsValue{}
}

var _ basetypes.ObjectValuable = AnalyticsRealtimeTopEventsValue{}

type AnalyticsRealtimeTopEventsValue struct {
	Count     basetypes.StringValue `tfsdk:"count"`
	EventType basetypes.StringValue `tfsdk:"event_type"`
	state     attr.ValueState
}

func (v AnalyticsRealtimeTopEventsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["count"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["event_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Count.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["count"] = val

		val, err = v.EventType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["event_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AnalyticsRealtimeTopEventsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AnalyticsRealtimeTopEventsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AnalyticsRealtimeTopEventsValue) String() string {
	return "AnalyticsRealtimeTopEventsValue"
}

func (v AnalyticsRealtimeTopEventsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"count":      basetypes.StringType{},
		"event_type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"count":      v.Count,
			"event_type": v.EventType,
		})

	return objVal, diags
}

func (v AnalyticsRealtimeTopEventsValue) Equal(o attr.Value) bool {
	other, ok := o.(AnalyticsRealtimeTopEventsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Count.Equal(other.Count) {
		return false
	}

	if !v.EventType.Equal(other.EventType) {
		return false
	}

	return true
}

func (v AnalyticsRealtimeTopEventsValue) Type(ctx context.Context) attr.Type {
	return AnalyticsRealtimeTopEventsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AnalyticsRealtimeTopEventsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"count":      basetypes.StringType{},
		"event_type": basetypes.StringType{},
	}
}
