// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AnalyticsTopVideosDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"limit": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"range_end": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"range_start": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"videos": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"avg_watch_time_ms": schema.Float64Attribute{
							Computed: true,
						},
						"completion_rate": schema.Float64Attribute{
							Computed: true,
						},
						"completions": schema.StringAttribute{
							Computed: true,
						},
						"starts": schema.StringAttribute{
							Computed: true,
						},
						"total_views": schema.StringAttribute{
							Computed: true,
						},
						"total_watch_time_ms": schema.Float64Attribute{
							Computed: true,
						},
						"unique_viewers": schema.StringAttribute{
							Computed: true,
						},
						"video_id": schema.StringAttribute{
							Computed: true,
						},
						"watches": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: AnalyticsTopVideosVideosType{
						ObjectType: types.ObjectType{
							AttrTypes: AnalyticsTopVideosVideosValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type AnalyticsTopVideosModel struct {
	Limit      types.Int64  `tfsdk:"limit"`
	RangeEnd   types.String `tfsdk:"range_end"`
	RangeStart types.String `tfsdk:"range_start"`
	Videos     types.List   `tfsdk:"videos"`
}

var _ basetypes.ObjectTypable = AnalyticsTopVideosVideosType{}

type AnalyticsTopVideosVideosType struct {
	basetypes.ObjectType
}

func (t AnalyticsTopVideosVideosType) Equal(o attr.Type) bool {
	other, ok := o.(AnalyticsTopVideosVideosType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AnalyticsTopVideosVideosType) String() string {
	return "AnalyticsTopVideosVideosType"
}

func (t AnalyticsTopVideosVideosType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	avgWatchTimeMsAttribute, ok := attributes["avg_watch_time_ms"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`avg_watch_time_ms is missing from object`)

		return nil, diags
	}

	avgWatchTimeMsVal, ok := avgWatchTimeMsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`avg_watch_time_ms expected to be basetypes.Float64Value, was: %T`, avgWatchTimeMsAttribute))
	}

	completionRateAttribute, ok := attributes["completion_rate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`completion_rate is missing from object`)

		return nil, diags
	}

	completionRateVal, ok := completionRateAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`completion_rate expected to be basetypes.Float64Value, was: %T`, completionRateAttribute))
	}

	completionsAttribute, ok := attributes["completions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`completions is missing from object`)

		return nil, diags
	}

	completionsVal, ok := completionsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`completions expected to be basetypes.StringValue, was: %T`, completionsAttribute))
	}

	startsAttribute, ok := attributes["starts"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`starts is missing from object`)

		return nil, diags
	}

	startsVal, ok := startsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`starts expected to be basetypes.StringValue, was: %T`, startsAttribute))
	}

	totalViewsAttribute, ok := attributes["total_views"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_views is missing from object`)

		return nil, diags
	}

	totalViewsVal, ok := totalViewsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_views expected to be basetypes.StringValue, was: %T`, totalViewsAttribute))
	}

	totalWatchTimeMsAttribute, ok := attributes["total_watch_time_ms"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_watch_time_ms is missing from object`)

		return nil, diags
	}

	totalWatchTimeMsVal, ok := totalWatchTimeMsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_watch_time_ms expected to be basetypes.Float64Value, was: %T`, totalWatchTimeMsAttribute))
	}

	uniqueViewersAttribute, ok := attributes["unique_viewers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unique_viewers is missing from object`)

		return nil, diags
	}

	uniqueViewersVal, ok := uniqueViewersAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unique_viewers expected to be basetypes.StringValue, was: %T`, uniqueViewersAttribute))
	}

	videoIdAttribute, ok := attributes["video_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`video_id is missing from object`)

		return nil, diags
	}

	videoIdVal, ok := videoIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`video_id expected to be basetypes.StringValue, was: %T`, videoIdAttribute))
	}

	watchesAttribute, ok := attributes["watches"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`watches is missing from object`)

		return nil, diags
	}

	watchesVal, ok := watchesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`watches expected to be basetypes.StringValue, was: %T`, watchesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AnalyticsTopVideosVideosValue{
		AvgWatchTimeMs:   avgWatchTimeMsVal,
		CompletionRate:   completionRateVal,
		Completions:      completionsVal,
		Starts:           startsVal,
		TotalViews:       totalViewsVal,
		TotalWatchTimeMs: totalWatchTimeMsVal,
		UniqueViewers:    uniqueViewersVal,
		VideoId:          videoIdVal,
		Watches:          watchesVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func AnalyticsTopVideosNewVideosValueNull() AnalyticsTopVideosVideosValue {
	return AnalyticsTopVideosVideosValue{
		state: attr.ValueStateNull,
	}
}

func AnalyticsTopVideosNewVideosValueUnknown() AnalyticsTopVideosVideosValue {
	return AnalyticsTopVideosVideosValue{
		state: attr.ValueStateUnknown,
	}
}

func AnalyticsTopVideosNewVideosValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AnalyticsTopVideosVideosValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AnalyticsTopVideosVideosValue Attribute Value",
				"While creating a AnalyticsTopVideosVideosValue value, a missing attribute value was detected. "+
					"A AnalyticsTopVideosVideosValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AnalyticsTopVideosVideosValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AnalyticsTopVideosVideosValue Attribute Type",
				"While creating a AnalyticsTopVideosVideosValue value, an invalid attribute value was detected. "+
					"A AnalyticsTopVideosVideosValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AnalyticsTopVideosVideosValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AnalyticsTopVideosVideosValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AnalyticsTopVideosVideosValue Attribute Value",
				"While creating a AnalyticsTopVideosVideosValue value, an extra attribute value was detected. "+
					"A AnalyticsTopVideosVideosValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AnalyticsTopVideosVideosValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	avgWatchTimeMsAttribute, ok := attributes["avg_watch_time_ms"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`avg_watch_time_ms is missing from object`)

		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	avgWatchTimeMsVal, ok := avgWatchTimeMsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`avg_watch_time_ms expected to be basetypes.Float64Value, was: %T`, avgWatchTimeMsAttribute))
	}

	completionRateAttribute, ok := attributes["completion_rate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`completion_rate is missing from object`)

		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	completionRateVal, ok := completionRateAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`completion_rate expected to be basetypes.Float64Value, was: %T`, completionRateAttribute))
	}

	completionsAttribute, ok := attributes["completions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`completions is missing from object`)

		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	completionsVal, ok := completionsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`completions expected to be basetypes.StringValue, was: %T`, completionsAttribute))
	}

	startsAttribute, ok := attributes["starts"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`starts is missing from object`)

		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	startsVal, ok := startsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`starts expected to be basetypes.StringValue, was: %T`, startsAttribute))
	}

	totalViewsAttribute, ok := attributes["total_views"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_views is missing from object`)

		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	totalViewsVal, ok := totalViewsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_views expected to be basetypes.StringValue, was: %T`, totalViewsAttribute))
	}

	totalWatchTimeMsAttribute, ok := attributes["total_watch_time_ms"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_watch_time_ms is missing from object`)

		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	totalWatchTimeMsVal, ok := totalWatchTimeMsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_watch_time_ms expected to be basetypes.Float64Value, was: %T`, totalWatchTimeMsAttribute))
	}

	uniqueViewersAttribute, ok := attributes["unique_viewers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unique_viewers is missing from object`)

		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	uniqueViewersVal, ok := uniqueViewersAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unique_viewers expected to be basetypes.StringValue, was: %T`, uniqueViewersAttribute))
	}

	videoIdAttribute, ok := attributes["video_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`video_id is missing from object`)

		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	videoIdVal, ok := videoIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`video_id expected to be basetypes.StringValue, was: %T`, videoIdAttribute))
	}

	watchesAttribute, ok := attributes["watches"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`watches is missing from object`)

		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	watchesVal, ok := watchesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`watches expected to be basetypes.StringValue, was: %T`, watchesAttribute))
	}

	if diags.HasError() {
		return AnalyticsTopVideosNewVideosValueUnknown(), diags
	}

	return AnalyticsTopVideosVideosValue{
		AvgWatchTimeMs:   avgWatchTimeMsVal,
		CompletionRate:   completionRateVal,
		Completions:      completionsVal,
		Starts:           startsVal,
		TotalViews:       totalViewsVal,
		TotalWatchTimeMs: totalWatchTimeMsVal,
		UniqueViewers:    uniqueViewersVal,
		VideoId:          videoIdVal,
		Watches:          watchesVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func AnalyticsTopVideosNewVideosValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AnalyticsTopVideosVideosValue {
	object, diags := AnalyticsTopVideosNewVideosValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("AnalyticsTopVideosNewVideosValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AnalyticsTopVideosVideosType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return AnalyticsTopVideosNewVideosValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return AnalyticsTopVideosNewVideosValueUnknown(), nil
	}

	if in.IsNull() {
		return AnalyticsTopVideosNewVideosValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return AnalyticsTopVideosNewVideosValueMust(AnalyticsTopVideosVideosValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AnalyticsTopVideosVideosType) ValueType(ctx context.Context) attr.Value {
	return AnalyticsTopVideosVideosValue{}
}

var _ basetypes.ObjectValuable = AnalyticsTopVideosVideosValue{}

type AnalyticsTopVideosVideosValue struct {
	AvgWatchTimeMs   basetypes.Float64Value `tfsdk:"avg_watch_time_ms"`
	CompletionRate   basetypes.Float64Value `tfsdk:"completion_rate"`
	Completions      basetypes.StringValue  `tfsdk:"completions"`
	Starts           basetypes.StringValue  `tfsdk:"starts"`
	TotalViews       basetypes.StringValue  `tfsdk:"total_views"`
	TotalWatchTimeMs basetypes.Float64Value `tfsdk:"total_watch_time_ms"`
	UniqueViewers    basetypes.StringValue  `tfsdk:"unique_viewers"`
	VideoId          basetypes.StringValue  `tfsdk:"video_id"`
	Watches          basetypes.StringValue  `tfsdk:"watches"`
	state            attr.ValueState
}

func (v AnalyticsTopVideosVideosValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 9)

	var val tftypes.Value
	var err error

	attrTypes["avg_watch_time_ms"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["completion_rate"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["completions"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["starts"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["total_views"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["total_watch_time_ms"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["unique_viewers"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["video_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["watches"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 9)

		val, err = v.AvgWatchTimeMs.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["avg_watch_time_ms"] = val

		val, err = v.CompletionRate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["completion_rate"] = val

		val, err = v.Completions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["completions"] = val

		val, err = v.Starts.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["starts"] = val

		val, err = v.TotalViews.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total_views"] = val

		val, err = v.TotalWatchTimeMs.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total_watch_time_ms"] = val

		val, err = v.UniqueViewers.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["unique_viewers"] = val

		val, err = v.VideoId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["video_id"] = val

		val, err = v.Watches.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["watches"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AnalyticsTopVideosVideosValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AnalyticsTopVideosVideosValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AnalyticsTopVideosVideosValue) String() string {
	return "AnalyticsTopVideosVideosValue"
}

func (v AnalyticsTopVideosVideosValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"avg_watch_time_ms":   basetypes.Float64Type{},
		"completion_rate":     basetypes.Float64Type{},
		"completions":         basetypes.StringType{},
		"starts":              basetypes.StringType{},
		"total_views":         basetypes.StringType{},
		"total_watch_time_ms": basetypes.Float64Type{},
		"unique_viewers":      basetypes.StringType{},
		"video_id":            basetypes.StringType{},
		"watches":             basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"avg_watch_time_ms":   v.AvgWatchTimeMs,
			"completion_rate":     v.CompletionRate,
			"completions":         v.Completions,
			"starts":              v.Starts,
			"total_views":         v.TotalViews,
			"total_watch_time_ms": v.TotalWatchTimeMs,
			"unique_viewers":      v.UniqueViewers,
			"video_id":            v.VideoId,
			"watches":             v.Watches,
		})

	return objVal, diags
}

func (v AnalyticsTopVideosVideosValue) Equal(o attr.Value) bool {
	other, ok := o.(AnalyticsTopVideosVideosValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AvgWatchTimeMs.Equal(other.AvgWatchTimeMs) {
		return false
	}

	if !v.CompletionRate.Equal(other.CompletionRate) {
		return false
	}

	if !v.Completions.Equal(other.Completions) {
		return false
	}

	if !v.Starts.Equal(other.Starts) {
		return false
	}

	if !v.TotalViews.Equal(other.TotalViews) {
		return false
	}

	if !v.TotalWatchTimeMs.Equal(other.TotalWatchTimeMs) {
		return false
	}

	if !v.UniqueViewers.Equal(other.UniqueViewers) {
		return false
	}

	if !v.VideoId.Equal(other.VideoId) {
		return false
	}

	if !v.Watches.Equal(other.Watches) {
		return false
	}

	return true
}

func (v AnalyticsTopVideosVideosValue) Type(ctx context.Context) attr.Type {
	return AnalyticsTopVideosVideosType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AnalyticsTopVideosVideosValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"avg_watch_time_ms":   basetypes.Float64Type{},
		"completion_rate":     basetypes.Float64Type{},
		"completions":         basetypes.StringType{},
		"starts":              basetypes.StringType{},
		"total_views":         basetypes.StringType{},
		"total_watch_time_ms": basetypes.Float64Type{},
		"unique_viewers":      basetypes.StringType{},
		"video_id":            basetypes.StringType{},
		"watches":             basetypes.StringType{},
	}
}
