// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AuthMembershipsOrgIdInfoDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.StringAttribute{
				Computed: true,
			},
			"org_id": schema.StringAttribute{
				Required:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"user_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
		},
	}
}

type AuthMembershipsOrgIdInfoModel struct {
	Email  types.String `tfsdk:"email"`
	OrgId  types.String `tfsdk:"org_id"`
	UserId types.String `tfsdk:"user_id"`
}
