// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func BillingPlanDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"currency": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "",
				MarkdownDescription: "",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"interval": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"price": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type BillingPlanModel struct {
	Currency    types.String `tfsdk:"currency"`
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Interval    types.String `tfsdk:"interval"`
	Name        types.String `tfsdk:"name"`
	Price       types.String `tfsdk:"price"`
}
