// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func BlogSubscriptionDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"subscribed": schema.BoolAttribute{
				Computed: true,
			},
			"subscribed_at": schema.StringAttribute{
				Computed:            true,
				Description:         "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
				MarkdownDescription: "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
			},
			"user_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type BlogSubscriptionDataSourceModel struct {
	Subscribed   types.Bool   `tfsdk:"subscribed"`
	SubscribedAt types.String `tfsdk:"subscribed_at"`
	UserId       types.String `tfsdk:"user_id"`
}
