// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DashboardStatsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"filterbrowsers": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"filtercities": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"filtercountries": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"filterdevices": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"filterlanguages": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"filteros": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"filteros_versions": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"filterregions": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"interval": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"points": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"timestamp": schema.StringAttribute{
							Computed: true,
						},
						"unique_users": schema.StringAttribute{
							Computed: true,
						},
						"views": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: DashboardStatsDataSourcePointsType{
						ObjectType: types.ObjectType{
							AttrTypes: DashboardStatsDataSourcePointsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"time_end": schema.StringAttribute{
				Required: true,
			},
			"time_start": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type DashboardStatsDataSourceModel struct {
	Filterbrowsers   types.List   `tfsdk:"filterbrowsers"`
	Filtercities     types.List   `tfsdk:"filtercities"`
	Filtercountries  types.List   `tfsdk:"filtercountries"`
	Filterdevices    types.List   `tfsdk:"filterdevices"`
	Filterlanguages  types.List   `tfsdk:"filterlanguages"`
	Filteros         types.List   `tfsdk:"filteros"`
	FilterosVersions types.List   `tfsdk:"filteros_versions"`
	Filterregions    types.List   `tfsdk:"filterregions"`
	Interval         types.String `tfsdk:"interval"`
	Points           types.List   `tfsdk:"points"`
	TimeEnd          types.String `tfsdk:"time_end"`
	TimeStart        types.String `tfsdk:"time_start"`
}

var _ basetypes.ObjectTypable = DashboardStatsDataSourcePointsType{}

type DashboardStatsDataSourcePointsType struct {
	basetypes.ObjectType
}

func (t DashboardStatsDataSourcePointsType) Equal(o attr.Type) bool {
	other, ok := o.(DashboardStatsDataSourcePointsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DashboardStatsDataSourcePointsType) String() string {
	return "PointsType"
}

func (t DashboardStatsDataSourcePointsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	timestampAttribute, ok := attributes["timestamp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`timestamp is missing from object`)

		return nil, diags
	}

	timestampVal, ok := timestampAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`timestamp expected to be basetypes.StringValue, was: %T`, timestampAttribute))
	}

	uniqueUsersAttribute, ok := attributes["unique_users"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unique_users is missing from object`)

		return nil, diags
	}

	uniqueUsersVal, ok := uniqueUsersAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unique_users expected to be basetypes.StringValue, was: %T`, uniqueUsersAttribute))
	}

	viewsAttribute, ok := attributes["views"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`views is missing from object`)

		return nil, diags
	}

	viewsVal, ok := viewsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`views expected to be basetypes.StringValue, was: %T`, viewsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DashboardStatsDataSourcePointsValue{
		Timestamp:   timestampVal,
		UniqueUsers: uniqueUsersVal,
		Views:       viewsVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewDashboardStatsDataSourcePointsValueNull() DashboardStatsDataSourcePointsValue {
	return DashboardStatsDataSourcePointsValue{
		state: attr.ValueStateNull,
	}
}

func NewDashboardStatsDataSourcePointsValueUnknown() DashboardStatsDataSourcePointsValue {
	return DashboardStatsDataSourcePointsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDashboardStatsDataSourcePointsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DashboardStatsDataSourcePointsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PointsValue Attribute Value",
				"While creating a PointsValue value, a missing attribute value was detected. "+
					"A PointsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PointsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PointsValue Attribute Type",
				"While creating a PointsValue value, an invalid attribute value was detected. "+
					"A PointsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PointsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PointsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PointsValue Attribute Value",
				"While creating a PointsValue value, an extra attribute value was detected. "+
					"A PointsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PointsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDashboardStatsDataSourcePointsValueUnknown(), diags
	}

	timestampAttribute, ok := attributes["timestamp"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`timestamp is missing from object`)

		return NewDashboardStatsDataSourcePointsValueUnknown(), diags
	}

	timestampVal, ok := timestampAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`timestamp expected to be basetypes.StringValue, was: %T`, timestampAttribute))
	}

	uniqueUsersAttribute, ok := attributes["unique_users"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unique_users is missing from object`)

		return NewDashboardStatsDataSourcePointsValueUnknown(), diags
	}

	uniqueUsersVal, ok := uniqueUsersAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unique_users expected to be basetypes.StringValue, was: %T`, uniqueUsersAttribute))
	}

	viewsAttribute, ok := attributes["views"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`views is missing from object`)

		return NewDashboardStatsDataSourcePointsValueUnknown(), diags
	}

	viewsVal, ok := viewsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`views expected to be basetypes.StringValue, was: %T`, viewsAttribute))
	}

	if diags.HasError() {
		return NewDashboardStatsDataSourcePointsValueUnknown(), diags
	}

	return DashboardStatsDataSourcePointsValue{
		Timestamp:   timestampVal,
		UniqueUsers: uniqueUsersVal,
		Views:       viewsVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewDashboardStatsDataSourcePointsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DashboardStatsDataSourcePointsValue {
	object, diags := NewDashboardStatsDataSourcePointsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPointsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DashboardStatsDataSourcePointsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDashboardStatsDataSourcePointsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDashboardStatsDataSourcePointsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDashboardStatsDataSourcePointsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDashboardStatsDataSourcePointsValueMust(DashboardStatsDataSourcePointsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DashboardStatsDataSourcePointsType) ValueType(ctx context.Context) attr.Value {
	return DashboardStatsDataSourcePointsValue{}
}

var _ basetypes.ObjectValuable = DashboardStatsDataSourcePointsValue{}

type DashboardStatsDataSourcePointsValue struct {
	Timestamp   basetypes.StringValue `tfsdk:"timestamp"`
	UniqueUsers basetypes.StringValue `tfsdk:"unique_users"`
	Views       basetypes.StringValue `tfsdk:"views"`
	state       attr.ValueState
}

func (v DashboardStatsDataSourcePointsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["timestamp"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["unique_users"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["views"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Timestamp.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["timestamp"] = val

		val, err = v.UniqueUsers.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["unique_users"] = val

		val, err = v.Views.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["views"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DashboardStatsDataSourcePointsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DashboardStatsDataSourcePointsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DashboardStatsDataSourcePointsValue) String() string {
	return "PointsValue"
}

func (v DashboardStatsDataSourcePointsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"timestamp":    basetypes.StringType{},
		"unique_users": basetypes.StringType{},
		"views":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"timestamp":    v.Timestamp,
			"unique_users": v.UniqueUsers,
			"views":        v.Views,
		})

	return objVal, diags
}

func (v DashboardStatsDataSourcePointsValue) Equal(o attr.Value) bool {
	other, ok := o.(DashboardStatsDataSourcePointsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Timestamp.Equal(other.Timestamp) {
		return false
	}

	if !v.UniqueUsers.Equal(other.UniqueUsers) {
		return false
	}

	if !v.Views.Equal(other.Views) {
		return false
	}

	return true
}

func (v DashboardStatsDataSourcePointsValue) Type(ctx context.Context) attr.Type {
	return DashboardStatsDataSourcePointsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DashboardStatsDataSourcePointsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"timestamp":    basetypes.StringType{},
		"unique_users": basetypes.StringType{},
		"views":        basetypes.StringType{},
	}
}
