// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func MediaProjectVideoChaptersDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"chapters": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"start_time_sec": schema.Float64Attribute{
							Computed: true,
						},
						"title": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: MediaProjectVideoChaptersChaptersType{
						ObjectType: types.ObjectType{
							AttrTypes: MediaProjectVideoChaptersChaptersValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"project_id": schema.StringAttribute{
				Required:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"video_id": schema.StringAttribute{
				Required:            true,
				Description:         "",
				MarkdownDescription: "",
			},
		},
	}
}

type MediaProjectVideoChaptersModel struct {
	Chapters  types.List   `tfsdk:"chapters"`
	ProjectId types.String `tfsdk:"project_id"`
	VideoId   types.String `tfsdk:"video_id"`
}

var _ basetypes.ObjectTypable = MediaProjectVideoChaptersChaptersType{}

type MediaProjectVideoChaptersChaptersType struct {
	basetypes.ObjectType
}

func (t MediaProjectVideoChaptersChaptersType) Equal(o attr.Type) bool {
	other, ok := o.(MediaProjectVideoChaptersChaptersType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MediaProjectVideoChaptersChaptersType) String() string {
	return "MediaProjectVideoChaptersChaptersType"
}

func (t MediaProjectVideoChaptersChaptersType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	startTimeSecAttribute, ok := attributes["start_time_sec"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_time_sec is missing from object`)

		return nil, diags
	}

	startTimeSecVal, ok := startTimeSecAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_time_sec expected to be basetypes.Float64Value, was: %T`, startTimeSecAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return nil, diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MediaProjectVideoChaptersChaptersValue{
		StartTimeSec: startTimeSecVal,
		Title:        titleVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func MediaProjectVideoChaptersNewChaptersValueNull() MediaProjectVideoChaptersChaptersValue {
	return MediaProjectVideoChaptersChaptersValue{
		state: attr.ValueStateNull,
	}
}

func MediaProjectVideoChaptersNewChaptersValueUnknown() MediaProjectVideoChaptersChaptersValue {
	return MediaProjectVideoChaptersChaptersValue{
		state: attr.ValueStateUnknown,
	}
}

func MediaProjectVideoChaptersNewChaptersValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MediaProjectVideoChaptersChaptersValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MediaProjectVideoChaptersChaptersValue Attribute Value",
				"While creating a MediaProjectVideoChaptersChaptersValue value, a missing attribute value was detected. "+
					"A MediaProjectVideoChaptersChaptersValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MediaProjectVideoChaptersChaptersValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MediaProjectVideoChaptersChaptersValue Attribute Type",
				"While creating a MediaProjectVideoChaptersChaptersValue value, an invalid attribute value was detected. "+
					"A MediaProjectVideoChaptersChaptersValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MediaProjectVideoChaptersChaptersValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MediaProjectVideoChaptersChaptersValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MediaProjectVideoChaptersChaptersValue Attribute Value",
				"While creating a MediaProjectVideoChaptersChaptersValue value, an extra attribute value was detected. "+
					"A MediaProjectVideoChaptersChaptersValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MediaProjectVideoChaptersChaptersValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return MediaProjectVideoChaptersNewChaptersValueUnknown(), diags
	}

	startTimeSecAttribute, ok := attributes["start_time_sec"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_time_sec is missing from object`)

		return MediaProjectVideoChaptersNewChaptersValueUnknown(), diags
	}

	startTimeSecVal, ok := startTimeSecAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_time_sec expected to be basetypes.Float64Value, was: %T`, startTimeSecAttribute))
	}

	titleAttribute, ok := attributes["title"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`title is missing from object`)

		return MediaProjectVideoChaptersNewChaptersValueUnknown(), diags
	}

	titleVal, ok := titleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`title expected to be basetypes.StringValue, was: %T`, titleAttribute))
	}

	if diags.HasError() {
		return MediaProjectVideoChaptersNewChaptersValueUnknown(), diags
	}

	return MediaProjectVideoChaptersChaptersValue{
		StartTimeSec: startTimeSecVal,
		Title:        titleVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func MediaProjectVideoChaptersNewChaptersValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MediaProjectVideoChaptersChaptersValue {
	object, diags := MediaProjectVideoChaptersNewChaptersValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("MediaProjectVideoChaptersNewChaptersValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MediaProjectVideoChaptersChaptersType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return MediaProjectVideoChaptersNewChaptersValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return MediaProjectVideoChaptersNewChaptersValueUnknown(), nil
	}

	if in.IsNull() {
		return MediaProjectVideoChaptersNewChaptersValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return MediaProjectVideoChaptersNewChaptersValueMust(MediaProjectVideoChaptersChaptersValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MediaProjectVideoChaptersChaptersType) ValueType(ctx context.Context) attr.Value {
	return MediaProjectVideoChaptersChaptersValue{}
}

var _ basetypes.ObjectValuable = MediaProjectVideoChaptersChaptersValue{}

type MediaProjectVideoChaptersChaptersValue struct {
	StartTimeSec basetypes.Float64Value `tfsdk:"start_time_sec"`
	Title        basetypes.StringValue  `tfsdk:"title"`
	state        attr.ValueState
}

func (v MediaProjectVideoChaptersChaptersValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["start_time_sec"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["title"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.StartTimeSec.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_time_sec"] = val

		val, err = v.Title.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["title"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MediaProjectVideoChaptersChaptersValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MediaProjectVideoChaptersChaptersValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MediaProjectVideoChaptersChaptersValue) String() string {
	return "MediaProjectVideoChaptersChaptersValue"
}

func (v MediaProjectVideoChaptersChaptersValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"start_time_sec": basetypes.Float64Type{},
		"title":          basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"start_time_sec": v.StartTimeSec,
			"title":          v.Title,
		})

	return objVal, diags
}

func (v MediaProjectVideoChaptersChaptersValue) Equal(o attr.Value) bool {
	other, ok := o.(MediaProjectVideoChaptersChaptersValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.StartTimeSec.Equal(other.StartTimeSec) {
		return false
	}

	if !v.Title.Equal(other.Title) {
		return false
	}

	return true
}

func (v MediaProjectVideoChaptersChaptersValue) Type(ctx context.Context) attr.Type {
	return MediaProjectVideoChaptersChaptersType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MediaProjectVideoChaptersChaptersValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"start_time_sec": basetypes.Float64Type{},
		"title":          basetypes.StringType{},
	}
}
