// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func MediaImageDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"attached_to_video": schema.BoolAttribute{
				Computed: true,
			},
			"file": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"format": schema.StringAttribute{
						Computed: true,
					},
					"id": schema.StringAttribute{
						Computed: true,
					},
					"name": schema.StringAttribute{
						Computed: true,
					},
					"project_id": schema.StringAttribute{
						Computed: true,
					},
					"size": schema.StringAttribute{
						Computed: true,
					},
					"status": schema.StringAttribute{
						Computed: true,
					},
					"url": schema.StringAttribute{
						Computed: true,
					},
				},
				CustomType: MediaImageMediaImageMediaImageFileType{
					ObjectType: types.ObjectType{
						AttrTypes: MediaImageMediaImageMediaImageFileValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"height": schema.Int64Attribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"thumbhash": schema.StringAttribute{
				Computed: true,
			},
			"visibility": schema.StringAttribute{
				Computed: true,
			},
			"width": schema.Int64Attribute{
				Computed: true,
			},
		},
	}
}

type MediaImageModel struct {
	AttachedToVideo types.Bool                              `tfsdk:"attached_to_video"`
	File            MediaImageMediaImageMediaImageFileValue `tfsdk:"file"`
	Height          types.Int64                             `tfsdk:"height"`
	Id              types.String                            `tfsdk:"id"`
	Thumbhash       types.String                            `tfsdk:"thumbhash"`
	Visibility      types.String                            `tfsdk:"visibility"`
	Width           types.Int64                             `tfsdk:"width"`
}

var _ basetypes.ObjectTypable = MediaImageMediaImageMediaImageFileType{}

type MediaImageMediaImageMediaImageFileType struct {
	basetypes.ObjectType
}

func (t MediaImageMediaImageMediaImageFileType) Equal(o attr.Type) bool {
	other, ok := o.(MediaImageMediaImageMediaImageFileType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t MediaImageMediaImageMediaImageFileType) String() string {
	return "MediaImageMediaImageMediaImageFileType"
}

func (t MediaImageMediaImageMediaImageFileType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	formatAttribute, ok := attributes["format"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`format is missing from object`)

		return nil, diags
	}

	formatVal, ok := formatAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`format expected to be basetypes.StringValue, was: %T`, formatAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	projectIdAttribute, ok := attributes["project_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_id is missing from object`)

		return nil, diags
	}

	projectIdVal, ok := projectIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_id expected to be basetypes.StringValue, was: %T`, projectIdAttribute))
	}

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`)

		return nil, diags
	}

	sizeVal, ok := sizeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be basetypes.StringValue, was: %T`, sizeAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return nil, diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return MediaImageMediaImageMediaImageFileValue{
		Format:    formatVal,
		Id:        idVal,
		Name:      nameVal,
		ProjectId: projectIdVal,
		Size:      sizeVal,
		Status:    statusVal,
		Url:       urlVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func MediaImageMediaImageMediaImageNewFileValueNull() MediaImageMediaImageMediaImageFileValue {
	return MediaImageMediaImageMediaImageFileValue{
		state: attr.ValueStateNull,
	}
}

func MediaImageMediaImageMediaImageNewFileValueUnknown() MediaImageMediaImageMediaImageFileValue {
	return MediaImageMediaImageMediaImageFileValue{
		state: attr.ValueStateUnknown,
	}
}

func MediaImageMediaImageMediaImageNewFileValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (MediaImageMediaImageMediaImageFileValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing MediaImageMediaImageMediaImageFileValue Attribute Value",
				"While creating a MediaImageMediaImageMediaImageFileValue value, a missing attribute value was detected. "+
					"A MediaImageMediaImageMediaImageFileValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MediaImageMediaImageMediaImageFileValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid MediaImageMediaImageMediaImageFileValue Attribute Type",
				"While creating a MediaImageMediaImageMediaImageFileValue value, an invalid attribute value was detected. "+
					"A MediaImageMediaImageMediaImageFileValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("MediaImageMediaImageMediaImageFileValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("MediaImageMediaImageMediaImageFileValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra MediaImageMediaImageMediaImageFileValue Attribute Value",
				"While creating a MediaImageMediaImageMediaImageFileValue value, an extra attribute value was detected. "+
					"A MediaImageMediaImageMediaImageFileValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra MediaImageMediaImageMediaImageFileValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return MediaImageMediaImageMediaImageNewFileValueUnknown(), diags
	}

	formatAttribute, ok := attributes["format"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`format is missing from object`)

		return MediaImageMediaImageMediaImageNewFileValueUnknown(), diags
	}

	formatVal, ok := formatAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`format expected to be basetypes.StringValue, was: %T`, formatAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return MediaImageMediaImageMediaImageNewFileValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return MediaImageMediaImageMediaImageNewFileValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	projectIdAttribute, ok := attributes["project_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_id is missing from object`)

		return MediaImageMediaImageMediaImageNewFileValueUnknown(), diags
	}

	projectIdVal, ok := projectIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_id expected to be basetypes.StringValue, was: %T`, projectIdAttribute))
	}

	sizeAttribute, ok := attributes["size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size is missing from object`)

		return MediaImageMediaImageMediaImageNewFileValueUnknown(), diags
	}

	sizeVal, ok := sizeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size expected to be basetypes.StringValue, was: %T`, sizeAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return MediaImageMediaImageMediaImageNewFileValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return MediaImageMediaImageMediaImageNewFileValueUnknown(), diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	if diags.HasError() {
		return MediaImageMediaImageMediaImageNewFileValueUnknown(), diags
	}

	return MediaImageMediaImageMediaImageFileValue{
		Format:    formatVal,
		Id:        idVal,
		Name:      nameVal,
		ProjectId: projectIdVal,
		Size:      sizeVal,
		Status:    statusVal,
		Url:       urlVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func MediaImageMediaImageMediaImageNewFileValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) MediaImageMediaImageMediaImageFileValue {
	object, diags := MediaImageMediaImageMediaImageNewFileValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("MediaImageMediaImageMediaImageNewFileValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t MediaImageMediaImageMediaImageFileType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return MediaImageMediaImageMediaImageNewFileValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return MediaImageMediaImageMediaImageNewFileValueUnknown(), nil
	}

	if in.IsNull() {
		return MediaImageMediaImageMediaImageNewFileValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return MediaImageMediaImageMediaImageNewFileValueMust(MediaImageMediaImageMediaImageFileValue{}.AttributeTypes(ctx), attributes), nil
}

func (t MediaImageMediaImageMediaImageFileType) ValueType(ctx context.Context) attr.Value {
	return MediaImageMediaImageMediaImageFileValue{}
}

var _ basetypes.ObjectValuable = MediaImageMediaImageMediaImageFileValue{}

type MediaImageMediaImageMediaImageFileValue struct {
	Format    basetypes.StringValue `tfsdk:"format"`
	Id        basetypes.StringValue `tfsdk:"id"`
	Name      basetypes.StringValue `tfsdk:"name"`
	ProjectId basetypes.StringValue `tfsdk:"project_id"`
	Size      basetypes.StringValue `tfsdk:"size"`
	Status    basetypes.StringValue `tfsdk:"status"`
	Url       basetypes.StringValue `tfsdk:"url"`
	state     attr.ValueState
}

func (v MediaImageMediaImageMediaImageFileValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["format"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["project_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["size"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["url"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.Format.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["format"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.ProjectId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["project_id"] = val

		val, err = v.Size.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.Url.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["url"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v MediaImageMediaImageMediaImageFileValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v MediaImageMediaImageMediaImageFileValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v MediaImageMediaImageMediaImageFileValue) String() string {
	return "MediaImageMediaImageMediaImageFileValue"
}

func (v MediaImageMediaImageMediaImageFileValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"format":     basetypes.StringType{},
		"id":         basetypes.StringType{},
		"name":       basetypes.StringType{},
		"project_id": basetypes.StringType{},
		"size":       basetypes.StringType{},
		"status":     basetypes.StringType{},
		"url":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"format":     v.Format,
			"id":         v.Id,
			"name":       v.Name,
			"project_id": v.ProjectId,
			"size":       v.Size,
			"status":     v.Status,
			"url":        v.Url,
		})

	return objVal, diags
}

func (v MediaImageMediaImageMediaImageFileValue) Equal(o attr.Value) bool {
	other, ok := o.(MediaImageMediaImageMediaImageFileValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Format.Equal(other.Format) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.ProjectId.Equal(other.ProjectId) {
		return false
	}

	if !v.Size.Equal(other.Size) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.Url.Equal(other.Url) {
		return false
	}

	return true
}

func (v MediaImageMediaImageMediaImageFileValue) Type(ctx context.Context) attr.Type {
	return MediaImageMediaImageMediaImageFileType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v MediaImageMediaImageMediaImageFileValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"format":     basetypes.StringType{},
		"id":         basetypes.StringType{},
		"name":       basetypes.StringType{},
		"project_id": basetypes.StringType{},
		"size":       basetypes.StringType{},
		"status":     basetypes.StringType{},
		"url":        basetypes.StringType{},
	}
}
