// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func PostStatsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"post_id": schema.StringAttribute{
				Required:            true,
				Description:         "",
				MarkdownDescription: "",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"rangeend": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"rangestart": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"total_views": schema.StringAttribute{
				Computed: true,
			},
			"unique_viewers": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type PostStatsDataSourceModel struct {
	PostId        types.String `tfsdk:"post_id"`
	Rangeend      types.String `tfsdk:"rangeend"`
	Rangestart    types.String `tfsdk:"rangestart"`
	TotalViews    types.String `tfsdk:"total_views"`
	UniqueViewers types.String `tfsdk:"unique_viewers"`
}
