// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ProjectsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"org_id": schema.StringAttribute{
				Required:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"projects": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"created_at": schema.StringAttribute{
							Computed:            true,
							Description:         "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
							MarkdownDescription: "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
						},
						"custom_domain": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"org_id": schema.StringAttribute{
							Computed: true,
						},
						"regions": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"updated_at": schema.StringAttribute{
							Computed:            true,
							Description:         "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
							MarkdownDescription: "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
						},
						"video_quality": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: ProjectsDataSourceType{
						ObjectType: types.ObjectType{
							AttrTypes: ProjectsDataSourceValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type ProjectsDataSourceModel struct {
	OrgId    types.String `tfsdk:"org_id"`
	Projects types.List   `tfsdk:"projects"`
}

var _ basetypes.ObjectTypable = ProjectsDataSourceType{}

type ProjectsDataSourceType struct {
	basetypes.ObjectType
}

func (t ProjectsDataSourceType) Equal(o attr.Type) bool {
	other, ok := o.(ProjectsDataSourceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ProjectsDataSourceType) String() string {
	return "ProjectsType"
}

func (t ProjectsDataSourceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	customDomainAttribute, ok := attributes["custom_domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_domain is missing from object`)

		return nil, diags
	}

	customDomainVal, ok := customDomainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_domain expected to be basetypes.StringValue, was: %T`, customDomainAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	orgIdAttribute, ok := attributes["org_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_id is missing from object`)

		return nil, diags
	}

	orgIdVal, ok := orgIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_id expected to be basetypes.StringValue, was: %T`, orgIdAttribute))
	}

	regionsAttribute, ok := attributes["regions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`regions is missing from object`)

		return nil, diags
	}

	regionsVal, ok := regionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`regions expected to be basetypes.ListValue, was: %T`, regionsAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return nil, diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	videoQualityAttribute, ok := attributes["video_quality"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`video_quality is missing from object`)

		return nil, diags
	}

	videoQualityVal, ok := videoQualityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`video_quality expected to be basetypes.StringValue, was: %T`, videoQualityAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ProjectsDataSourceValue{
		CreatedAt:    createdAtVal,
		CustomDomain: customDomainVal,
		Id:           idVal,
		Name:         nameVal,
		OrgId:        orgIdVal,
		Regions:      regionsVal,
		UpdatedAt:    updatedAtVal,
		VideoQuality: videoQualityVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewProjectsDataSourceValueNull() ProjectsDataSourceValue {
	return ProjectsDataSourceValue{
		state: attr.ValueStateNull,
	}
}

func NewProjectsDataSourceValueUnknown() ProjectsDataSourceValue {
	return ProjectsDataSourceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewProjectsDataSourceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ProjectsDataSourceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ProjectsValue Attribute Value",
				"While creating a ProjectsValue value, a missing attribute value was detected. "+
					"A ProjectsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProjectsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ProjectsValue Attribute Type",
				"While creating a ProjectsValue value, an invalid attribute value was detected. "+
					"A ProjectsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProjectsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ProjectsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ProjectsValue Attribute Value",
				"While creating a ProjectsValue value, an extra attribute value was detected. "+
					"A ProjectsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ProjectsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewProjectsDataSourceValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewProjectsDataSourceValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	customDomainAttribute, ok := attributes["custom_domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_domain is missing from object`)

		return NewProjectsDataSourceValueUnknown(), diags
	}

	customDomainVal, ok := customDomainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_domain expected to be basetypes.StringValue, was: %T`, customDomainAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewProjectsDataSourceValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewProjectsDataSourceValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	orgIdAttribute, ok := attributes["org_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_id is missing from object`)

		return NewProjectsDataSourceValueUnknown(), diags
	}

	orgIdVal, ok := orgIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_id expected to be basetypes.StringValue, was: %T`, orgIdAttribute))
	}

	regionsAttribute, ok := attributes["regions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`regions is missing from object`)

		return NewProjectsDataSourceValueUnknown(), diags
	}

	regionsVal, ok := regionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`regions expected to be basetypes.ListValue, was: %T`, regionsAttribute))
	}

	updatedAtAttribute, ok := attributes["updated_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`updated_at is missing from object`)

		return NewProjectsDataSourceValueUnknown(), diags
	}

	updatedAtVal, ok := updatedAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`updated_at expected to be basetypes.StringValue, was: %T`, updatedAtAttribute))
	}

	videoQualityAttribute, ok := attributes["video_quality"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`video_quality is missing from object`)

		return NewProjectsDataSourceValueUnknown(), diags
	}

	videoQualityVal, ok := videoQualityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`video_quality expected to be basetypes.StringValue, was: %T`, videoQualityAttribute))
	}

	if diags.HasError() {
		return NewProjectsDataSourceValueUnknown(), diags
	}

	return ProjectsDataSourceValue{
		CreatedAt:    createdAtVal,
		CustomDomain: customDomainVal,
		Id:           idVal,
		Name:         nameVal,
		OrgId:        orgIdVal,
		Regions:      regionsVal,
		UpdatedAt:    updatedAtVal,
		VideoQuality: videoQualityVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewProjectsDataSourceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ProjectsDataSourceValue {
	object, diags := NewProjectsDataSourceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewProjectsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ProjectsDataSourceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewProjectsDataSourceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewProjectsDataSourceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewProjectsDataSourceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewProjectsDataSourceValueMust(ProjectsDataSourceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ProjectsDataSourceType) ValueType(ctx context.Context) attr.Value {
	return ProjectsDataSourceValue{}
}

var _ basetypes.ObjectValuable = ProjectsDataSourceValue{}

type ProjectsDataSourceValue struct {
	CreatedAt    basetypes.StringValue `tfsdk:"created_at"`
	CustomDomain basetypes.StringValue `tfsdk:"custom_domain"`
	Id           basetypes.StringValue `tfsdk:"id"`
	Name         basetypes.StringValue `tfsdk:"name"`
	OrgId        basetypes.StringValue `tfsdk:"org_id"`
	Regions      basetypes.ListValue   `tfsdk:"regions"`
	UpdatedAt    basetypes.StringValue `tfsdk:"updated_at"`
	VideoQuality basetypes.StringValue `tfsdk:"video_quality"`
	state        attr.ValueState
}

func (v ProjectsDataSourceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["custom_domain"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["org_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["regions"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["updated_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["video_quality"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.CustomDomain.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["custom_domain"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OrgId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["org_id"] = val

		val, err = v.Regions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["regions"] = val

		val, err = v.UpdatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["updated_at"] = val

		val, err = v.VideoQuality.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["video_quality"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ProjectsDataSourceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ProjectsDataSourceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ProjectsDataSourceValue) String() string {
	return "ProjectsValue"
}

func (v ProjectsDataSourceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var regionsVal basetypes.ListValue
	switch {
	case v.Regions.IsUnknown():
		regionsVal = types.ListUnknown(types.StringType)
	case v.Regions.IsNull():
		regionsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		regionsVal, d = types.ListValue(types.StringType, v.Regions.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"created_at":    basetypes.StringType{},
			"custom_domain": basetypes.StringType{},
			"id":            basetypes.StringType{},
			"name":          basetypes.StringType{},
			"org_id":        basetypes.StringType{},
			"regions": basetypes.ListType{
				ElemType: types.StringType,
			},
			"updated_at":    basetypes.StringType{},
			"video_quality": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"created_at":    basetypes.StringType{},
		"custom_domain": basetypes.StringType{},
		"id":            basetypes.StringType{},
		"name":          basetypes.StringType{},
		"org_id":        basetypes.StringType{},
		"regions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"updated_at":    basetypes.StringType{},
		"video_quality": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":    v.CreatedAt,
			"custom_domain": v.CustomDomain,
			"id":            v.Id,
			"name":          v.Name,
			"org_id":        v.OrgId,
			"regions":       regionsVal,
			"updated_at":    v.UpdatedAt,
			"video_quality": v.VideoQuality,
		})

	return objVal, diags
}

func (v ProjectsDataSourceValue) Equal(o attr.Value) bool {
	other, ok := o.(ProjectsDataSourceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.CustomDomain.Equal(other.CustomDomain) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OrgId.Equal(other.OrgId) {
		return false
	}

	if !v.Regions.Equal(other.Regions) {
		return false
	}

	if !v.UpdatedAt.Equal(other.UpdatedAt) {
		return false
	}

	if !v.VideoQuality.Equal(other.VideoQuality) {
		return false
	}

	return true
}

func (v ProjectsDataSourceValue) Type(ctx context.Context) attr.Type {
	return ProjectsDataSourceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ProjectsDataSourceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":    basetypes.StringType{},
		"custom_domain": basetypes.StringType{},
		"id":            basetypes.StringType{},
		"name":          basetypes.StringType{},
		"org_id":        basetypes.StringType{},
		"regions": basetypes.ListType{
			ElemType: types.StringType,
		},
		"updated_at":    basetypes.StringType{},
		"video_quality": basetypes.StringType{},
	}
}
