// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ProvidersDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"providers": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"email_address": schema.StringAttribute{
							Computed: true,
						},
						"first_name": schema.StringAttribute{
							Computed: true,
						},
						"image_url": schema.StringAttribute{
							Computed: true,
						},
						"last_name": schema.StringAttribute{
							Computed: true,
						},
						"provider": schema.StringAttribute{
							Computed: true,
						},
						"username": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: ProvidersDataSourceType{
						ObjectType: types.ObjectType{
							AttrTypes: ProvidersDataSourceValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"user_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type ProvidersDataSourceModel struct {
	Providers types.List   `tfsdk:"providers"`
	UserId    types.String `tfsdk:"user_id"`
}

var _ basetypes.ObjectTypable = ProvidersDataSourceType{}

type ProvidersDataSourceType struct {
	basetypes.ObjectType
}

func (t ProvidersDataSourceType) Equal(o attr.Type) bool {
	other, ok := o.(ProvidersDataSourceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ProvidersDataSourceType) String() string {
	return "ProvidersType"
}

func (t ProvidersDataSourceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	emailAddressAttribute, ok := attributes["email_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email_address is missing from object`)

		return nil, diags
	}

	emailAddressVal, ok := emailAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email_address expected to be basetypes.StringValue, was: %T`, emailAddressAttribute))
	}

	firstNameAttribute, ok := attributes["first_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`first_name is missing from object`)

		return nil, diags
	}

	firstNameVal, ok := firstNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`first_name expected to be basetypes.StringValue, was: %T`, firstNameAttribute))
	}

	imageUrlAttribute, ok := attributes["image_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_url is missing from object`)

		return nil, diags
	}

	imageUrlVal, ok := imageUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_url expected to be basetypes.StringValue, was: %T`, imageUrlAttribute))
	}

	lastNameAttribute, ok := attributes["last_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_name is missing from object`)

		return nil, diags
	}

	lastNameVal, ok := lastNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_name expected to be basetypes.StringValue, was: %T`, lastNameAttribute))
	}

	providerAttribute, ok := attributes["provider"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provider is missing from object`)

		return nil, diags
	}

	providerVal, ok := providerAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provider expected to be basetypes.StringValue, was: %T`, providerAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return nil, diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ProvidersDataSourceValue{
		EmailAddress: emailAddressVal,
		FirstName:    firstNameVal,
		ImageUrl:     imageUrlVal,
		LastName:     lastNameVal,
		Provider:     providerVal,
		Username:     usernameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewProvidersDataSourceValueNull() ProvidersDataSourceValue {
	return ProvidersDataSourceValue{
		state: attr.ValueStateNull,
	}
}

func NewProvidersDataSourceValueUnknown() ProvidersDataSourceValue {
	return ProvidersDataSourceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewProvidersDataSourceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ProvidersDataSourceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ProvidersValue Attribute Value",
				"While creating a ProvidersValue value, a missing attribute value was detected. "+
					"A ProvidersValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProvidersValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ProvidersValue Attribute Type",
				"While creating a ProvidersValue value, an invalid attribute value was detected. "+
					"A ProvidersValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProvidersValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ProvidersValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ProvidersValue Attribute Value",
				"While creating a ProvidersValue value, an extra attribute value was detected. "+
					"A ProvidersValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ProvidersValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewProvidersDataSourceValueUnknown(), diags
	}

	emailAddressAttribute, ok := attributes["email_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`email_address is missing from object`)

		return NewProvidersDataSourceValueUnknown(), diags
	}

	emailAddressVal, ok := emailAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`email_address expected to be basetypes.StringValue, was: %T`, emailAddressAttribute))
	}

	firstNameAttribute, ok := attributes["first_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`first_name is missing from object`)

		return NewProvidersDataSourceValueUnknown(), diags
	}

	firstNameVal, ok := firstNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`first_name expected to be basetypes.StringValue, was: %T`, firstNameAttribute))
	}

	imageUrlAttribute, ok := attributes["image_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_url is missing from object`)

		return NewProvidersDataSourceValueUnknown(), diags
	}

	imageUrlVal, ok := imageUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_url expected to be basetypes.StringValue, was: %T`, imageUrlAttribute))
	}

	lastNameAttribute, ok := attributes["last_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_name is missing from object`)

		return NewProvidersDataSourceValueUnknown(), diags
	}

	lastNameVal, ok := lastNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_name expected to be basetypes.StringValue, was: %T`, lastNameAttribute))
	}

	providerAttribute, ok := attributes["provider"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provider is missing from object`)

		return NewProvidersDataSourceValueUnknown(), diags
	}

	providerVal, ok := providerAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provider expected to be basetypes.StringValue, was: %T`, providerAttribute))
	}

	usernameAttribute, ok := attributes["username"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`username is missing from object`)

		return NewProvidersDataSourceValueUnknown(), diags
	}

	usernameVal, ok := usernameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`username expected to be basetypes.StringValue, was: %T`, usernameAttribute))
	}

	if diags.HasError() {
		return NewProvidersDataSourceValueUnknown(), diags
	}

	return ProvidersDataSourceValue{
		EmailAddress: emailAddressVal,
		FirstName:    firstNameVal,
		ImageUrl:     imageUrlVal,
		LastName:     lastNameVal,
		Provider:     providerVal,
		Username:     usernameVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewProvidersDataSourceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ProvidersDataSourceValue {
	object, diags := NewProvidersDataSourceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewProvidersValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ProvidersDataSourceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewProvidersDataSourceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewProvidersDataSourceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewProvidersDataSourceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewProvidersDataSourceValueMust(ProvidersDataSourceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ProvidersDataSourceType) ValueType(ctx context.Context) attr.Value {
	return ProvidersDataSourceValue{}
}

var _ basetypes.ObjectValuable = ProvidersDataSourceValue{}

type ProvidersDataSourceValue struct {
	EmailAddress basetypes.StringValue `tfsdk:"email_address"`
	FirstName    basetypes.StringValue `tfsdk:"first_name"`
	ImageUrl     basetypes.StringValue `tfsdk:"image_url"`
	LastName     basetypes.StringValue `tfsdk:"last_name"`
	Provider     basetypes.StringValue `tfsdk:"provider"`
	Username     basetypes.StringValue `tfsdk:"username"`
	state        attr.ValueState
}

func (v ProvidersDataSourceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["email_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["first_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["image_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["provider"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["username"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.EmailAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["email_address"] = val

		val, err = v.FirstName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["first_name"] = val

		val, err = v.ImageUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["image_url"] = val

		val, err = v.LastName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_name"] = val

		val, err = v.Provider.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["provider"] = val

		val, err = v.Username.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["username"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ProvidersDataSourceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ProvidersDataSourceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ProvidersDataSourceValue) String() string {
	return "ProvidersValue"
}

func (v ProvidersDataSourceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"email_address": basetypes.StringType{},
		"first_name":    basetypes.StringType{},
		"image_url":     basetypes.StringType{},
		"last_name":     basetypes.StringType{},
		"provider":      basetypes.StringType{},
		"username":      basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"email_address": v.EmailAddress,
			"first_name":    v.FirstName,
			"image_url":     v.ImageUrl,
			"last_name":     v.LastName,
			"provider":      v.Provider,
			"username":      v.Username,
		})

	return objVal, diags
}

func (v ProvidersDataSourceValue) Equal(o attr.Value) bool {
	other, ok := o.(ProvidersDataSourceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.EmailAddress.Equal(other.EmailAddress) {
		return false
	}

	if !v.FirstName.Equal(other.FirstName) {
		return false
	}

	if !v.ImageUrl.Equal(other.ImageUrl) {
		return false
	}

	if !v.LastName.Equal(other.LastName) {
		return false
	}

	if !v.Provider.Equal(other.Provider) {
		return false
	}

	if !v.Username.Equal(other.Username) {
		return false
	}

	return true
}

func (v ProvidersDataSourceValue) Type(ctx context.Context) attr.Type {
	return ProvidersDataSourceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ProvidersDataSourceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"email_address": basetypes.StringType{},
		"first_name":    basetypes.StringType{},
		"image_url":     basetypes.StringType{},
		"last_name":     basetypes.StringType{},
		"provider":      basetypes.StringType{},
		"username":      basetypes.StringType{},
	}
}
