// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func StorageUsageHistoryDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"days": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(1, 365),
				},
			},
			"org_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"total": schema.Int64Attribute{
				Computed: true,
			},
			"usages": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"image_file_count": schema.Int64Attribute{
							Computed: true,
						},
						"image_storage_bytes": schema.StringAttribute{
							Computed: true,
						},
						"last_updated": schema.StringAttribute{
							Computed:            true,
							Description:         "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
							MarkdownDescription: "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
						},
						"max_image_count": schema.Int64Attribute{
							Computed: true,
						},
						"max_project_count": schema.Int64Attribute{
							Computed: true,
						},
						"max_video_count": schema.Int64Attribute{
							Computed: true,
						},
						"org_id": schema.StringAttribute{
							Computed: true,
						},
						"project_count": schema.Int64Attribute{
							Computed: true,
						},
						"snapshot_date": schema.StringAttribute{
							Computed:            true,
							Description:         "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
							MarkdownDescription: "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
						},
						"total_file_count": schema.Int64Attribute{
							Computed: true,
						},
						"total_storage_bytes": schema.StringAttribute{
							Computed: true,
						},
						"total_video_minutes": schema.StringAttribute{
							Computed: true,
						},
						"video_file_count": schema.Int64Attribute{
							Computed: true,
						},
						"video_storage_bytes": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: StorageUsageHistoryDataSourceUsagesType{
						ObjectType: types.ObjectType{
							AttrTypes: StorageUsageHistoryDataSourceUsagesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type StorageUsageHistoryDataSourceModel struct {
	Days   types.Int64  `tfsdk:"days"`
	OrgId  types.String `tfsdk:"org_id"`
	Total  types.Int64  `tfsdk:"total"`
	Usages types.List   `tfsdk:"usages"`
}

var _ basetypes.ObjectTypable = StorageUsageHistoryDataSourceUsagesType{}

type StorageUsageHistoryDataSourceUsagesType struct {
	basetypes.ObjectType
}

func (t StorageUsageHistoryDataSourceUsagesType) Equal(o attr.Type) bool {
	other, ok := o.(StorageUsageHistoryDataSourceUsagesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t StorageUsageHistoryDataSourceUsagesType) String() string {
	return "UsagesType"
}

func (t StorageUsageHistoryDataSourceUsagesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	imageFileCountAttribute, ok := attributes["image_file_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_file_count is missing from object`)

		return nil, diags
	}

	imageFileCountVal, ok := imageFileCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_file_count expected to be basetypes.Int64Value, was: %T`, imageFileCountAttribute))
	}

	imageStorageBytesAttribute, ok := attributes["image_storage_bytes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_storage_bytes is missing from object`)

		return nil, diags
	}

	imageStorageBytesVal, ok := imageStorageBytesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_storage_bytes expected to be basetypes.StringValue, was: %T`, imageStorageBytesAttribute))
	}

	lastUpdatedAttribute, ok := attributes["last_updated"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_updated is missing from object`)

		return nil, diags
	}

	lastUpdatedVal, ok := lastUpdatedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_updated expected to be basetypes.StringValue, was: %T`, lastUpdatedAttribute))
	}

	maxImageCountAttribute, ok := attributes["max_image_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_image_count is missing from object`)

		return nil, diags
	}

	maxImageCountVal, ok := maxImageCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_image_count expected to be basetypes.Int64Value, was: %T`, maxImageCountAttribute))
	}

	maxProjectCountAttribute, ok := attributes["max_project_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_project_count is missing from object`)

		return nil, diags
	}

	maxProjectCountVal, ok := maxProjectCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_project_count expected to be basetypes.Int64Value, was: %T`, maxProjectCountAttribute))
	}

	maxVideoCountAttribute, ok := attributes["max_video_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_video_count is missing from object`)

		return nil, diags
	}

	maxVideoCountVal, ok := maxVideoCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_video_count expected to be basetypes.Int64Value, was: %T`, maxVideoCountAttribute))
	}

	orgIdAttribute, ok := attributes["org_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_id is missing from object`)

		return nil, diags
	}

	orgIdVal, ok := orgIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_id expected to be basetypes.StringValue, was: %T`, orgIdAttribute))
	}

	projectCountAttribute, ok := attributes["project_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_count is missing from object`)

		return nil, diags
	}

	projectCountVal, ok := projectCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_count expected to be basetypes.Int64Value, was: %T`, projectCountAttribute))
	}

	snapshotDateAttribute, ok := attributes["snapshot_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`snapshot_date is missing from object`)

		return nil, diags
	}

	snapshotDateVal, ok := snapshotDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`snapshot_date expected to be basetypes.StringValue, was: %T`, snapshotDateAttribute))
	}

	totalFileCountAttribute, ok := attributes["total_file_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_file_count is missing from object`)

		return nil, diags
	}

	totalFileCountVal, ok := totalFileCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_file_count expected to be basetypes.Int64Value, was: %T`, totalFileCountAttribute))
	}

	totalStorageBytesAttribute, ok := attributes["total_storage_bytes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_storage_bytes is missing from object`)

		return nil, diags
	}

	totalStorageBytesVal, ok := totalStorageBytesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_storage_bytes expected to be basetypes.StringValue, was: %T`, totalStorageBytesAttribute))
	}

	totalVideoMinutesAttribute, ok := attributes["total_video_minutes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_video_minutes is missing from object`)

		return nil, diags
	}

	totalVideoMinutesVal, ok := totalVideoMinutesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_video_minutes expected to be basetypes.StringValue, was: %T`, totalVideoMinutesAttribute))
	}

	videoFileCountAttribute, ok := attributes["video_file_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`video_file_count is missing from object`)

		return nil, diags
	}

	videoFileCountVal, ok := videoFileCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`video_file_count expected to be basetypes.Int64Value, was: %T`, videoFileCountAttribute))
	}

	videoStorageBytesAttribute, ok := attributes["video_storage_bytes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`video_storage_bytes is missing from object`)

		return nil, diags
	}

	videoStorageBytesVal, ok := videoStorageBytesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`video_storage_bytes expected to be basetypes.StringValue, was: %T`, videoStorageBytesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return StorageUsageHistoryDataSourceUsagesValue{
		ImageFileCount:    imageFileCountVal,
		ImageStorageBytes: imageStorageBytesVal,
		LastUpdated:       lastUpdatedVal,
		MaxImageCount:     maxImageCountVal,
		MaxProjectCount:   maxProjectCountVal,
		MaxVideoCount:     maxVideoCountVal,
		OrgId:             orgIdVal,
		ProjectCount:      projectCountVal,
		SnapshotDate:      snapshotDateVal,
		TotalFileCount:    totalFileCountVal,
		TotalStorageBytes: totalStorageBytesVal,
		TotalVideoMinutes: totalVideoMinutesVal,
		VideoFileCount:    videoFileCountVal,
		VideoStorageBytes: videoStorageBytesVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewStorageUsageHistoryDataSourceUsagesValueNull() StorageUsageHistoryDataSourceUsagesValue {
	return StorageUsageHistoryDataSourceUsagesValue{
		state: attr.ValueStateNull,
	}
}

func NewStorageUsageHistoryDataSourceUsagesValueUnknown() StorageUsageHistoryDataSourceUsagesValue {
	return StorageUsageHistoryDataSourceUsagesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewStorageUsageHistoryDataSourceUsagesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (StorageUsageHistoryDataSourceUsagesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UsagesValue Attribute Value",
				"While creating a UsagesValue value, a missing attribute value was detected. "+
					"A UsagesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UsagesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UsagesValue Attribute Type",
				"While creating a UsagesValue value, an invalid attribute value was detected. "+
					"A UsagesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UsagesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UsagesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UsagesValue Attribute Value",
				"While creating a UsagesValue value, an extra attribute value was detected. "+
					"A UsagesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UsagesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	imageFileCountAttribute, ok := attributes["image_file_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_file_count is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	imageFileCountVal, ok := imageFileCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_file_count expected to be basetypes.Int64Value, was: %T`, imageFileCountAttribute))
	}

	imageStorageBytesAttribute, ok := attributes["image_storage_bytes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`image_storage_bytes is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	imageStorageBytesVal, ok := imageStorageBytesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`image_storage_bytes expected to be basetypes.StringValue, was: %T`, imageStorageBytesAttribute))
	}

	lastUpdatedAttribute, ok := attributes["last_updated"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_updated is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	lastUpdatedVal, ok := lastUpdatedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_updated expected to be basetypes.StringValue, was: %T`, lastUpdatedAttribute))
	}

	maxImageCountAttribute, ok := attributes["max_image_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_image_count is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	maxImageCountVal, ok := maxImageCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_image_count expected to be basetypes.Int64Value, was: %T`, maxImageCountAttribute))
	}

	maxProjectCountAttribute, ok := attributes["max_project_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_project_count is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	maxProjectCountVal, ok := maxProjectCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_project_count expected to be basetypes.Int64Value, was: %T`, maxProjectCountAttribute))
	}

	maxVideoCountAttribute, ok := attributes["max_video_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max_video_count is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	maxVideoCountVal, ok := maxVideoCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max_video_count expected to be basetypes.Int64Value, was: %T`, maxVideoCountAttribute))
	}

	orgIdAttribute, ok := attributes["org_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_id is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	orgIdVal, ok := orgIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_id expected to be basetypes.StringValue, was: %T`, orgIdAttribute))
	}

	projectCountAttribute, ok := attributes["project_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`project_count is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	projectCountVal, ok := projectCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`project_count expected to be basetypes.Int64Value, was: %T`, projectCountAttribute))
	}

	snapshotDateAttribute, ok := attributes["snapshot_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`snapshot_date is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	snapshotDateVal, ok := snapshotDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`snapshot_date expected to be basetypes.StringValue, was: %T`, snapshotDateAttribute))
	}

	totalFileCountAttribute, ok := attributes["total_file_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_file_count is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	totalFileCountVal, ok := totalFileCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_file_count expected to be basetypes.Int64Value, was: %T`, totalFileCountAttribute))
	}

	totalStorageBytesAttribute, ok := attributes["total_storage_bytes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_storage_bytes is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	totalStorageBytesVal, ok := totalStorageBytesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_storage_bytes expected to be basetypes.StringValue, was: %T`, totalStorageBytesAttribute))
	}

	totalVideoMinutesAttribute, ok := attributes["total_video_minutes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_video_minutes is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	totalVideoMinutesVal, ok := totalVideoMinutesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_video_minutes expected to be basetypes.StringValue, was: %T`, totalVideoMinutesAttribute))
	}

	videoFileCountAttribute, ok := attributes["video_file_count"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`video_file_count is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	videoFileCountVal, ok := videoFileCountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`video_file_count expected to be basetypes.Int64Value, was: %T`, videoFileCountAttribute))
	}

	videoStorageBytesAttribute, ok := attributes["video_storage_bytes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`video_storage_bytes is missing from object`)

		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	videoStorageBytesVal, ok := videoStorageBytesAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`video_storage_bytes expected to be basetypes.StringValue, was: %T`, videoStorageBytesAttribute))
	}

	if diags.HasError() {
		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), diags
	}

	return StorageUsageHistoryDataSourceUsagesValue{
		ImageFileCount:    imageFileCountVal,
		ImageStorageBytes: imageStorageBytesVal,
		LastUpdated:       lastUpdatedVal,
		MaxImageCount:     maxImageCountVal,
		MaxProjectCount:   maxProjectCountVal,
		MaxVideoCount:     maxVideoCountVal,
		OrgId:             orgIdVal,
		ProjectCount:      projectCountVal,
		SnapshotDate:      snapshotDateVal,
		TotalFileCount:    totalFileCountVal,
		TotalStorageBytes: totalStorageBytesVal,
		TotalVideoMinutes: totalVideoMinutesVal,
		VideoFileCount:    videoFileCountVal,
		VideoStorageBytes: videoStorageBytesVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewStorageUsageHistoryDataSourceUsagesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) StorageUsageHistoryDataSourceUsagesValue {
	object, diags := NewStorageUsageHistoryDataSourceUsagesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUsagesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t StorageUsageHistoryDataSourceUsagesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewStorageUsageHistoryDataSourceUsagesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewStorageUsageHistoryDataSourceUsagesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewStorageUsageHistoryDataSourceUsagesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewStorageUsageHistoryDataSourceUsagesValueMust(StorageUsageHistoryDataSourceUsagesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t StorageUsageHistoryDataSourceUsagesType) ValueType(ctx context.Context) attr.Value {
	return StorageUsageHistoryDataSourceUsagesValue{}
}

var _ basetypes.ObjectValuable = StorageUsageHistoryDataSourceUsagesValue{}

type StorageUsageHistoryDataSourceUsagesValue struct {
	ImageFileCount    basetypes.Int64Value  `tfsdk:"image_file_count"`
	ImageStorageBytes basetypes.StringValue `tfsdk:"image_storage_bytes"`
	LastUpdated       basetypes.StringValue `tfsdk:"last_updated"`
	MaxImageCount     basetypes.Int64Value  `tfsdk:"max_image_count"`
	MaxProjectCount   basetypes.Int64Value  `tfsdk:"max_project_count"`
	MaxVideoCount     basetypes.Int64Value  `tfsdk:"max_video_count"`
	OrgId             basetypes.StringValue `tfsdk:"org_id"`
	ProjectCount      basetypes.Int64Value  `tfsdk:"project_count"`
	SnapshotDate      basetypes.StringValue `tfsdk:"snapshot_date"`
	TotalFileCount    basetypes.Int64Value  `tfsdk:"total_file_count"`
	TotalStorageBytes basetypes.StringValue `tfsdk:"total_storage_bytes"`
	TotalVideoMinutes basetypes.StringValue `tfsdk:"total_video_minutes"`
	VideoFileCount    basetypes.Int64Value  `tfsdk:"video_file_count"`
	VideoStorageBytes basetypes.StringValue `tfsdk:"video_storage_bytes"`
	state             attr.ValueState
}

func (v StorageUsageHistoryDataSourceUsagesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 14)

	var val tftypes.Value
	var err error

	attrTypes["image_file_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["image_storage_bytes"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_updated"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["max_image_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["max_project_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["max_video_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["org_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["project_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["snapshot_date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["total_file_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["total_storage_bytes"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["total_video_minutes"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["video_file_count"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["video_storage_bytes"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 14)

		val, err = v.ImageFileCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["image_file_count"] = val

		val, err = v.ImageStorageBytes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["image_storage_bytes"] = val

		val, err = v.LastUpdated.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_updated"] = val

		val, err = v.MaxImageCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_image_count"] = val

		val, err = v.MaxProjectCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_project_count"] = val

		val, err = v.MaxVideoCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max_video_count"] = val

		val, err = v.OrgId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["org_id"] = val

		val, err = v.ProjectCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["project_count"] = val

		val, err = v.SnapshotDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["snapshot_date"] = val

		val, err = v.TotalFileCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total_file_count"] = val

		val, err = v.TotalStorageBytes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total_storage_bytes"] = val

		val, err = v.TotalVideoMinutes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total_video_minutes"] = val

		val, err = v.VideoFileCount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["video_file_count"] = val

		val, err = v.VideoStorageBytes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["video_storage_bytes"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v StorageUsageHistoryDataSourceUsagesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v StorageUsageHistoryDataSourceUsagesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v StorageUsageHistoryDataSourceUsagesValue) String() string {
	return "UsagesValue"
}

func (v StorageUsageHistoryDataSourceUsagesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"image_file_count":    basetypes.Int64Type{},
		"image_storage_bytes": basetypes.StringType{},
		"last_updated":        basetypes.StringType{},
		"max_image_count":     basetypes.Int64Type{},
		"max_project_count":   basetypes.Int64Type{},
		"max_video_count":     basetypes.Int64Type{},
		"org_id":              basetypes.StringType{},
		"project_count":       basetypes.Int64Type{},
		"snapshot_date":       basetypes.StringType{},
		"total_file_count":    basetypes.Int64Type{},
		"total_storage_bytes": basetypes.StringType{},
		"total_video_minutes": basetypes.StringType{},
		"video_file_count":    basetypes.Int64Type{},
		"video_storage_bytes": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"image_file_count":    v.ImageFileCount,
			"image_storage_bytes": v.ImageStorageBytes,
			"last_updated":        v.LastUpdated,
			"max_image_count":     v.MaxImageCount,
			"max_project_count":   v.MaxProjectCount,
			"max_video_count":     v.MaxVideoCount,
			"org_id":              v.OrgId,
			"project_count":       v.ProjectCount,
			"snapshot_date":       v.SnapshotDate,
			"total_file_count":    v.TotalFileCount,
			"total_storage_bytes": v.TotalStorageBytes,
			"total_video_minutes": v.TotalVideoMinutes,
			"video_file_count":    v.VideoFileCount,
			"video_storage_bytes": v.VideoStorageBytes,
		})

	return objVal, diags
}

func (v StorageUsageHistoryDataSourceUsagesValue) Equal(o attr.Value) bool {
	other, ok := o.(StorageUsageHistoryDataSourceUsagesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ImageFileCount.Equal(other.ImageFileCount) {
		return false
	}

	if !v.ImageStorageBytes.Equal(other.ImageStorageBytes) {
		return false
	}

	if !v.LastUpdated.Equal(other.LastUpdated) {
		return false
	}

	if !v.MaxImageCount.Equal(other.MaxImageCount) {
		return false
	}

	if !v.MaxProjectCount.Equal(other.MaxProjectCount) {
		return false
	}

	if !v.MaxVideoCount.Equal(other.MaxVideoCount) {
		return false
	}

	if !v.OrgId.Equal(other.OrgId) {
		return false
	}

	if !v.ProjectCount.Equal(other.ProjectCount) {
		return false
	}

	if !v.SnapshotDate.Equal(other.SnapshotDate) {
		return false
	}

	if !v.TotalFileCount.Equal(other.TotalFileCount) {
		return false
	}

	if !v.TotalStorageBytes.Equal(other.TotalStorageBytes) {
		return false
	}

	if !v.TotalVideoMinutes.Equal(other.TotalVideoMinutes) {
		return false
	}

	if !v.VideoFileCount.Equal(other.VideoFileCount) {
		return false
	}

	if !v.VideoStorageBytes.Equal(other.VideoStorageBytes) {
		return false
	}

	return true
}

func (v StorageUsageHistoryDataSourceUsagesValue) Type(ctx context.Context) attr.Type {
	return StorageUsageHistoryDataSourceUsagesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v StorageUsageHistoryDataSourceUsagesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"image_file_count":    basetypes.Int64Type{},
		"image_storage_bytes": basetypes.StringType{},
		"last_updated":        basetypes.StringType{},
		"max_image_count":     basetypes.Int64Type{},
		"max_project_count":   basetypes.Int64Type{},
		"max_video_count":     basetypes.Int64Type{},
		"org_id":              basetypes.StringType{},
		"project_count":       basetypes.Int64Type{},
		"snapshot_date":       basetypes.StringType{},
		"total_file_count":    basetypes.Int64Type{},
		"total_storage_bytes": basetypes.StringType{},
		"total_video_minutes": basetypes.StringType{},
		"video_file_count":    basetypes.Int64Type{},
		"video_storage_bytes": basetypes.StringType{},
	}
}
