// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SubscriptionHistoryDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"items": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"cancel_at_period_end": schema.BoolAttribute{
							Computed: true,
						},
						"created_at": schema.StringAttribute{
							Computed:            true,
							Description:         "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
							MarkdownDescription: "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
						},
						"currency": schema.StringAttribute{
							Computed: true,
						},
						"current_period_end": schema.StringAttribute{
							Computed:            true,
							Description:         "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
							MarkdownDescription: "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
						},
						"end_date": schema.StringAttribute{
							Computed:            true,
							Description:         "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
							MarkdownDescription: "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"org_id": schema.StringAttribute{
							Computed: true,
						},
						"plan_id": schema.StringAttribute{
							Computed: true,
						},
						"plan_name": schema.StringAttribute{
							Computed: true,
						},
						"price": schema.StringAttribute{
							Computed: true,
						},
						"start_date": schema.StringAttribute{
							Computed:            true,
							Description:         "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
							MarkdownDescription: "RFC 3339 timestamp, e.g. \"2024-12-25T12:00:00Z\".",
						},
						"status": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: SubscriptionHistoryDataSourceItemsType{
						ObjectType: types.ObjectType{
							AttrTypes: SubscriptionHistoryDataSourceItemsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"org_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"paginationlimit": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Maximum number of items to return.",
				MarkdownDescription: "Maximum number of items to return.",
				Validators: []validator.Int64{
					int64validator.Between(1, 100),
				},
			},
			"paginationoffset": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Number of items to skip before collecting the result set.",
				MarkdownDescription: "Number of items to skip before collecting the result set.",
			},
		},
	}
}

type SubscriptionHistoryDataSourceModel struct {
	Items            types.List   `tfsdk:"items"`
	OrgId            types.String `tfsdk:"org_id"`
	Paginationlimit  types.Int64  `tfsdk:"paginationlimit"`
	Paginationoffset types.Int64  `tfsdk:"paginationoffset"`
}

var _ basetypes.ObjectTypable = SubscriptionHistoryDataSourceItemsType{}

type SubscriptionHistoryDataSourceItemsType struct {
	basetypes.ObjectType
}

func (t SubscriptionHistoryDataSourceItemsType) Equal(o attr.Type) bool {
	other, ok := o.(SubscriptionHistoryDataSourceItemsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SubscriptionHistoryDataSourceItemsType) String() string {
	return "ItemsType"
}

func (t SubscriptionHistoryDataSourceItemsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	cancelAtPeriodEndAttribute, ok := attributes["cancel_at_period_end"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cancel_at_period_end is missing from object`)

		return nil, diags
	}

	cancelAtPeriodEndVal, ok := cancelAtPeriodEndAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cancel_at_period_end expected to be basetypes.BoolValue, was: %T`, cancelAtPeriodEndAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	currencyAttribute, ok := attributes["currency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`currency is missing from object`)

		return nil, diags
	}

	currencyVal, ok := currencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`currency expected to be basetypes.StringValue, was: %T`, currencyAttribute))
	}

	currentPeriodEndAttribute, ok := attributes["current_period_end"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`current_period_end is missing from object`)

		return nil, diags
	}

	currentPeriodEndVal, ok := currentPeriodEndAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`current_period_end expected to be basetypes.StringValue, was: %T`, currentPeriodEndAttribute))
	}

	endDateAttribute, ok := attributes["end_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_date is missing from object`)

		return nil, diags
	}

	endDateVal, ok := endDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_date expected to be basetypes.StringValue, was: %T`, endDateAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	orgIdAttribute, ok := attributes["org_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_id is missing from object`)

		return nil, diags
	}

	orgIdVal, ok := orgIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_id expected to be basetypes.StringValue, was: %T`, orgIdAttribute))
	}

	planIdAttribute, ok := attributes["plan_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_id is missing from object`)

		return nil, diags
	}

	planIdVal, ok := planIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_id expected to be basetypes.StringValue, was: %T`, planIdAttribute))
	}

	planNameAttribute, ok := attributes["plan_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_name is missing from object`)

		return nil, diags
	}

	planNameVal, ok := planNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_name expected to be basetypes.StringValue, was: %T`, planNameAttribute))
	}

	priceAttribute, ok := attributes["price"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`price is missing from object`)

		return nil, diags
	}

	priceVal, ok := priceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`price expected to be basetypes.StringValue, was: %T`, priceAttribute))
	}

	startDateAttribute, ok := attributes["start_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_date is missing from object`)

		return nil, diags
	}

	startDateVal, ok := startDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_date expected to be basetypes.StringValue, was: %T`, startDateAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SubscriptionHistoryDataSourceItemsValue{
		CancelAtPeriodEnd: cancelAtPeriodEndVal,
		CreatedAt:         createdAtVal,
		Currency:          currencyVal,
		CurrentPeriodEnd:  currentPeriodEndVal,
		EndDate:           endDateVal,
		Id:                idVal,
		OrgId:             orgIdVal,
		PlanId:            planIdVal,
		PlanName:          planNameVal,
		Price:             priceVal,
		StartDate:         startDateVal,
		Status:            statusVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewSubscriptionHistoryDataSourceItemsValueNull() SubscriptionHistoryDataSourceItemsValue {
	return SubscriptionHistoryDataSourceItemsValue{
		state: attr.ValueStateNull,
	}
}

func NewSubscriptionHistoryDataSourceItemsValueUnknown() SubscriptionHistoryDataSourceItemsValue {
	return SubscriptionHistoryDataSourceItemsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSubscriptionHistoryDataSourceItemsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SubscriptionHistoryDataSourceItemsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ItemsValue Attribute Value",
				"While creating a ItemsValue value, a missing attribute value was detected. "+
					"A ItemsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ItemsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ItemsValue Attribute Type",
				"While creating a ItemsValue value, an invalid attribute value was detected. "+
					"A ItemsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ItemsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ItemsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ItemsValue Attribute Value",
				"While creating a ItemsValue value, an extra attribute value was detected. "+
					"A ItemsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ItemsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	cancelAtPeriodEndAttribute, ok := attributes["cancel_at_period_end"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cancel_at_period_end is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	cancelAtPeriodEndVal, ok := cancelAtPeriodEndAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cancel_at_period_end expected to be basetypes.BoolValue, was: %T`, cancelAtPeriodEndAttribute))
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	currencyAttribute, ok := attributes["currency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`currency is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	currencyVal, ok := currencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`currency expected to be basetypes.StringValue, was: %T`, currencyAttribute))
	}

	currentPeriodEndAttribute, ok := attributes["current_period_end"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`current_period_end is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	currentPeriodEndVal, ok := currentPeriodEndAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`current_period_end expected to be basetypes.StringValue, was: %T`, currentPeriodEndAttribute))
	}

	endDateAttribute, ok := attributes["end_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_date is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	endDateVal, ok := endDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_date expected to be basetypes.StringValue, was: %T`, endDateAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	orgIdAttribute, ok := attributes["org_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`org_id is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	orgIdVal, ok := orgIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`org_id expected to be basetypes.StringValue, was: %T`, orgIdAttribute))
	}

	planIdAttribute, ok := attributes["plan_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_id is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	planIdVal, ok := planIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_id expected to be basetypes.StringValue, was: %T`, planIdAttribute))
	}

	planNameAttribute, ok := attributes["plan_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_name is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	planNameVal, ok := planNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_name expected to be basetypes.StringValue, was: %T`, planNameAttribute))
	}

	priceAttribute, ok := attributes["price"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`price is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	priceVal, ok := priceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`price expected to be basetypes.StringValue, was: %T`, priceAttribute))
	}

	startDateAttribute, ok := attributes["start_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_date is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	startDateVal, ok := startDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_date expected to be basetypes.StringValue, was: %T`, startDateAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), diags
	}

	return SubscriptionHistoryDataSourceItemsValue{
		CancelAtPeriodEnd: cancelAtPeriodEndVal,
		CreatedAt:         createdAtVal,
		Currency:          currencyVal,
		CurrentPeriodEnd:  currentPeriodEndVal,
		EndDate:           endDateVal,
		Id:                idVal,
		OrgId:             orgIdVal,
		PlanId:            planIdVal,
		PlanName:          planNameVal,
		Price:             priceVal,
		StartDate:         startDateVal,
		Status:            statusVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewSubscriptionHistoryDataSourceItemsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SubscriptionHistoryDataSourceItemsValue {
	object, diags := NewSubscriptionHistoryDataSourceItemsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewItemsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SubscriptionHistoryDataSourceItemsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSubscriptionHistoryDataSourceItemsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSubscriptionHistoryDataSourceItemsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSubscriptionHistoryDataSourceItemsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSubscriptionHistoryDataSourceItemsValueMust(SubscriptionHistoryDataSourceItemsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SubscriptionHistoryDataSourceItemsType) ValueType(ctx context.Context) attr.Value {
	return SubscriptionHistoryDataSourceItemsValue{}
}

var _ basetypes.ObjectValuable = SubscriptionHistoryDataSourceItemsValue{}

type SubscriptionHistoryDataSourceItemsValue struct {
	CancelAtPeriodEnd basetypes.BoolValue   `tfsdk:"cancel_at_period_end"`
	CreatedAt         basetypes.StringValue `tfsdk:"created_at"`
	Currency          basetypes.StringValue `tfsdk:"currency"`
	CurrentPeriodEnd  basetypes.StringValue `tfsdk:"current_period_end"`
	EndDate           basetypes.StringValue `tfsdk:"end_date"`
	Id                basetypes.StringValue `tfsdk:"id"`
	OrgId             basetypes.StringValue `tfsdk:"org_id"`
	PlanId            basetypes.StringValue `tfsdk:"plan_id"`
	PlanName          basetypes.StringValue `tfsdk:"plan_name"`
	Price             basetypes.StringValue `tfsdk:"price"`
	StartDate         basetypes.StringValue `tfsdk:"start_date"`
	Status            basetypes.StringValue `tfsdk:"status"`
	state             attr.ValueState
}

func (v SubscriptionHistoryDataSourceItemsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 12)

	var val tftypes.Value
	var err error

	attrTypes["cancel_at_period_end"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["currency"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["current_period_end"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["end_date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["org_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["plan_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["plan_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["price"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["start_date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 12)

		val, err = v.CancelAtPeriodEnd.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cancel_at_period_end"] = val

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Currency.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["currency"] = val

		val, err = v.CurrentPeriodEnd.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["current_period_end"] = val

		val, err = v.EndDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_date"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.OrgId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["org_id"] = val

		val, err = v.PlanId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["plan_id"] = val

		val, err = v.PlanName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["plan_name"] = val

		val, err = v.Price.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["price"] = val

		val, err = v.StartDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_date"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SubscriptionHistoryDataSourceItemsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SubscriptionHistoryDataSourceItemsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SubscriptionHistoryDataSourceItemsValue) String() string {
	return "ItemsValue"
}

func (v SubscriptionHistoryDataSourceItemsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"cancel_at_period_end": basetypes.BoolType{},
		"created_at":           basetypes.StringType{},
		"currency":             basetypes.StringType{},
		"current_period_end":   basetypes.StringType{},
		"end_date":             basetypes.StringType{},
		"id":                   basetypes.StringType{},
		"org_id":               basetypes.StringType{},
		"plan_id":              basetypes.StringType{},
		"plan_name":            basetypes.StringType{},
		"price":                basetypes.StringType{},
		"start_date":           basetypes.StringType{},
		"status":               basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"cancel_at_period_end": v.CancelAtPeriodEnd,
			"created_at":           v.CreatedAt,
			"currency":             v.Currency,
			"current_period_end":   v.CurrentPeriodEnd,
			"end_date":             v.EndDate,
			"id":                   v.Id,
			"org_id":               v.OrgId,
			"plan_id":              v.PlanId,
			"plan_name":            v.PlanName,
			"price":                v.Price,
			"start_date":           v.StartDate,
			"status":               v.Status,
		})

	return objVal, diags
}

func (v SubscriptionHistoryDataSourceItemsValue) Equal(o attr.Value) bool {
	other, ok := o.(SubscriptionHistoryDataSourceItemsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CancelAtPeriodEnd.Equal(other.CancelAtPeriodEnd) {
		return false
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Currency.Equal(other.Currency) {
		return false
	}

	if !v.CurrentPeriodEnd.Equal(other.CurrentPeriodEnd) {
		return false
	}

	if !v.EndDate.Equal(other.EndDate) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.OrgId.Equal(other.OrgId) {
		return false
	}

	if !v.PlanId.Equal(other.PlanId) {
		return false
	}

	if !v.PlanName.Equal(other.PlanName) {
		return false
	}

	if !v.Price.Equal(other.Price) {
		return false
	}

	if !v.StartDate.Equal(other.StartDate) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	return true
}

func (v SubscriptionHistoryDataSourceItemsValue) Type(ctx context.Context) attr.Type {
	return SubscriptionHistoryDataSourceItemsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SubscriptionHistoryDataSourceItemsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"cancel_at_period_end": basetypes.BoolType{},
		"created_at":           basetypes.StringType{},
		"currency":             basetypes.StringType{},
		"current_period_end":   basetypes.StringType{},
		"end_date":             basetypes.StringType{},
		"id":                   basetypes.StringType{},
		"org_id":               basetypes.StringType{},
		"plan_id":              basetypes.StringType{},
		"plan_name":            basetypes.StringType{},
		"price":                basetypes.StringType{},
		"start_date":           basetypes.StringType{},
		"status":               basetypes.StringType{},
	}
}
