// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func TopFeedsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"feeds": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"avg_time_per_visit_ms": schema.Float64Attribute{
							Computed: true,
						},
						"feed_id": schema.StringAttribute{
							Computed: true,
						},
						"total_posts": schema.StringAttribute{
							Computed: true,
						},
						"total_views": schema.StringAttribute{
							Computed: true,
						},
						"total_watch_time_ms": schema.Float64Attribute{
							Computed: true,
						},
						"unique_viewers": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: TopFeedsDataSourceFeedsType{
						ObjectType: types.ObjectType{
							AttrTypes: TopFeedsDataSourceFeedsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"limit": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"rangeend": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"rangestart": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type TopFeedsDataSourceModel struct {
	Feeds      types.List   `tfsdk:"feeds"`
	Limit      types.Int64  `tfsdk:"limit"`
	Rangeend   types.String `tfsdk:"rangeend"`
	Rangestart types.String `tfsdk:"rangestart"`
}

var _ basetypes.ObjectTypable = TopFeedsDataSourceFeedsType{}

type TopFeedsDataSourceFeedsType struct {
	basetypes.ObjectType
}

func (t TopFeedsDataSourceFeedsType) Equal(o attr.Type) bool {
	other, ok := o.(TopFeedsDataSourceFeedsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TopFeedsDataSourceFeedsType) String() string {
	return "FeedsType"
}

func (t TopFeedsDataSourceFeedsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	avgTimePerVisitMsAttribute, ok := attributes["avg_time_per_visit_ms"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`avg_time_per_visit_ms is missing from object`)

		return nil, diags
	}

	avgTimePerVisitMsVal, ok := avgTimePerVisitMsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`avg_time_per_visit_ms expected to be basetypes.Float64Value, was: %T`, avgTimePerVisitMsAttribute))
	}

	feedIdAttribute, ok := attributes["feed_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`feed_id is missing from object`)

		return nil, diags
	}

	feedIdVal, ok := feedIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`feed_id expected to be basetypes.StringValue, was: %T`, feedIdAttribute))
	}

	totalPostsAttribute, ok := attributes["total_posts"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_posts is missing from object`)

		return nil, diags
	}

	totalPostsVal, ok := totalPostsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_posts expected to be basetypes.StringValue, was: %T`, totalPostsAttribute))
	}

	totalViewsAttribute, ok := attributes["total_views"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_views is missing from object`)

		return nil, diags
	}

	totalViewsVal, ok := totalViewsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_views expected to be basetypes.StringValue, was: %T`, totalViewsAttribute))
	}

	totalWatchTimeMsAttribute, ok := attributes["total_watch_time_ms"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_watch_time_ms is missing from object`)

		return nil, diags
	}

	totalWatchTimeMsVal, ok := totalWatchTimeMsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_watch_time_ms expected to be basetypes.Float64Value, was: %T`, totalWatchTimeMsAttribute))
	}

	uniqueViewersAttribute, ok := attributes["unique_viewers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unique_viewers is missing from object`)

		return nil, diags
	}

	uniqueViewersVal, ok := uniqueViewersAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unique_viewers expected to be basetypes.StringValue, was: %T`, uniqueViewersAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TopFeedsDataSourceFeedsValue{
		AvgTimePerVisitMs: avgTimePerVisitMsVal,
		FeedId:            feedIdVal,
		TotalPosts:        totalPostsVal,
		TotalViews:        totalViewsVal,
		TotalWatchTimeMs:  totalWatchTimeMsVal,
		UniqueViewers:     uniqueViewersVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewTopFeedsDataSourceFeedsValueNull() TopFeedsDataSourceFeedsValue {
	return TopFeedsDataSourceFeedsValue{
		state: attr.ValueStateNull,
	}
}

func NewTopFeedsDataSourceFeedsValueUnknown() TopFeedsDataSourceFeedsValue {
	return TopFeedsDataSourceFeedsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTopFeedsDataSourceFeedsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TopFeedsDataSourceFeedsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing FeedsValue Attribute Value",
				"While creating a FeedsValue value, a missing attribute value was detected. "+
					"A FeedsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("FeedsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid FeedsValue Attribute Type",
				"While creating a FeedsValue value, an invalid attribute value was detected. "+
					"A FeedsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("FeedsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("FeedsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra FeedsValue Attribute Value",
				"While creating a FeedsValue value, an extra attribute value was detected. "+
					"A FeedsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra FeedsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTopFeedsDataSourceFeedsValueUnknown(), diags
	}

	avgTimePerVisitMsAttribute, ok := attributes["avg_time_per_visit_ms"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`avg_time_per_visit_ms is missing from object`)

		return NewTopFeedsDataSourceFeedsValueUnknown(), diags
	}

	avgTimePerVisitMsVal, ok := avgTimePerVisitMsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`avg_time_per_visit_ms expected to be basetypes.Float64Value, was: %T`, avgTimePerVisitMsAttribute))
	}

	feedIdAttribute, ok := attributes["feed_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`feed_id is missing from object`)

		return NewTopFeedsDataSourceFeedsValueUnknown(), diags
	}

	feedIdVal, ok := feedIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`feed_id expected to be basetypes.StringValue, was: %T`, feedIdAttribute))
	}

	totalPostsAttribute, ok := attributes["total_posts"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_posts is missing from object`)

		return NewTopFeedsDataSourceFeedsValueUnknown(), diags
	}

	totalPostsVal, ok := totalPostsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_posts expected to be basetypes.StringValue, was: %T`, totalPostsAttribute))
	}

	totalViewsAttribute, ok := attributes["total_views"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_views is missing from object`)

		return NewTopFeedsDataSourceFeedsValueUnknown(), diags
	}

	totalViewsVal, ok := totalViewsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_views expected to be basetypes.StringValue, was: %T`, totalViewsAttribute))
	}

	totalWatchTimeMsAttribute, ok := attributes["total_watch_time_ms"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total_watch_time_ms is missing from object`)

		return NewTopFeedsDataSourceFeedsValueUnknown(), diags
	}

	totalWatchTimeMsVal, ok := totalWatchTimeMsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total_watch_time_ms expected to be basetypes.Float64Value, was: %T`, totalWatchTimeMsAttribute))
	}

	uniqueViewersAttribute, ok := attributes["unique_viewers"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`unique_viewers is missing from object`)

		return NewTopFeedsDataSourceFeedsValueUnknown(), diags
	}

	uniqueViewersVal, ok := uniqueViewersAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`unique_viewers expected to be basetypes.StringValue, was: %T`, uniqueViewersAttribute))
	}

	if diags.HasError() {
		return NewTopFeedsDataSourceFeedsValueUnknown(), diags
	}

	return TopFeedsDataSourceFeedsValue{
		AvgTimePerVisitMs: avgTimePerVisitMsVal,
		FeedId:            feedIdVal,
		TotalPosts:        totalPostsVal,
		TotalViews:        totalViewsVal,
		TotalWatchTimeMs:  totalWatchTimeMsVal,
		UniqueViewers:     uniqueViewersVal,
		state:             attr.ValueStateKnown,
	}, diags
}

func NewTopFeedsDataSourceFeedsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TopFeedsDataSourceFeedsValue {
	object, diags := NewTopFeedsDataSourceFeedsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewFeedsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TopFeedsDataSourceFeedsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTopFeedsDataSourceFeedsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTopFeedsDataSourceFeedsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTopFeedsDataSourceFeedsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTopFeedsDataSourceFeedsValueMust(TopFeedsDataSourceFeedsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TopFeedsDataSourceFeedsType) ValueType(ctx context.Context) attr.Value {
	return TopFeedsDataSourceFeedsValue{}
}

var _ basetypes.ObjectValuable = TopFeedsDataSourceFeedsValue{}

type TopFeedsDataSourceFeedsValue struct {
	AvgTimePerVisitMs basetypes.Float64Value `tfsdk:"avg_time_per_visit_ms"`
	FeedId            basetypes.StringValue  `tfsdk:"feed_id"`
	TotalPosts        basetypes.StringValue  `tfsdk:"total_posts"`
	TotalViews        basetypes.StringValue  `tfsdk:"total_views"`
	TotalWatchTimeMs  basetypes.Float64Value `tfsdk:"total_watch_time_ms"`
	UniqueViewers     basetypes.StringValue  `tfsdk:"unique_viewers"`
	state             attr.ValueState
}

func (v TopFeedsDataSourceFeedsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["avg_time_per_visit_ms"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["feed_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["total_posts"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["total_views"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["total_watch_time_ms"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["unique_viewers"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.AvgTimePerVisitMs.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["avg_time_per_visit_ms"] = val

		val, err = v.FeedId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["feed_id"] = val

		val, err = v.TotalPosts.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total_posts"] = val

		val, err = v.TotalViews.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total_views"] = val

		val, err = v.TotalWatchTimeMs.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total_watch_time_ms"] = val

		val, err = v.UniqueViewers.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["unique_viewers"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TopFeedsDataSourceFeedsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TopFeedsDataSourceFeedsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TopFeedsDataSourceFeedsValue) String() string {
	return "FeedsValue"
}

func (v TopFeedsDataSourceFeedsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"avg_time_per_visit_ms": basetypes.Float64Type{},
		"feed_id":               basetypes.StringType{},
		"total_posts":           basetypes.StringType{},
		"total_views":           basetypes.StringType{},
		"total_watch_time_ms":   basetypes.Float64Type{},
		"unique_viewers":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"avg_time_per_visit_ms": v.AvgTimePerVisitMs,
			"feed_id":               v.FeedId,
			"total_posts":           v.TotalPosts,
			"total_views":           v.TotalViews,
			"total_watch_time_ms":   v.TotalWatchTimeMs,
			"unique_viewers":        v.UniqueViewers,
		})

	return objVal, diags
}

func (v TopFeedsDataSourceFeedsValue) Equal(o attr.Value) bool {
	other, ok := o.(TopFeedsDataSourceFeedsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AvgTimePerVisitMs.Equal(other.AvgTimePerVisitMs) {
		return false
	}

	if !v.FeedId.Equal(other.FeedId) {
		return false
	}

	if !v.TotalPosts.Equal(other.TotalPosts) {
		return false
	}

	if !v.TotalViews.Equal(other.TotalViews) {
		return false
	}

	if !v.TotalWatchTimeMs.Equal(other.TotalWatchTimeMs) {
		return false
	}

	if !v.UniqueViewers.Equal(other.UniqueViewers) {
		return false
	}

	return true
}

func (v TopFeedsDataSourceFeedsValue) Type(ctx context.Context) attr.Type {
	return TopFeedsDataSourceFeedsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TopFeedsDataSourceFeedsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"avg_time_per_visit_ms": basetypes.Float64Type{},
		"feed_id":               basetypes.StringType{},
		"total_posts":           basetypes.StringType{},
		"total_views":           basetypes.StringType{},
		"total_watch_time_ms":   basetypes.Float64Type{},
		"unique_viewers":        basetypes.StringType{},
	}
}
