// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func UserDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.StringAttribute{
				Computed: true,
			},
			"email_verified": schema.BoolAttribute{
				Computed: true,
			},
			"user_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type UserDataSourceModel struct {
	Email         types.String `tfsdk:"email"`
	EmailVerified types.Bool   `tfsdk:"email_verified"`
	UserId        types.String `tfsdk:"user_id"`
}
