// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func VideoHotSegmentsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"rangeend": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"rangestart": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"segments": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"end_second": schema.Int64Attribute{
							Computed: true,
						},
						"multiplier": schema.Float64Attribute{
							Computed: true,
						},
						"start_second": schema.Int64Attribute{
							Computed: true,
						},
					},
					CustomType: VideoHotSegmentsDataSourceSegmentsType{
						ObjectType: types.ObjectType{
							AttrTypes: VideoHotSegmentsDataSourceSegmentsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"video_id": schema.StringAttribute{
				Required:            true,
				Description:         "",
				MarkdownDescription: "",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
		},
	}
}

type VideoHotSegmentsDataSourceModel struct {
	Rangeend   types.String `tfsdk:"rangeend"`
	Rangestart types.String `tfsdk:"rangestart"`
	Segments   types.List   `tfsdk:"segments"`
	VideoId    types.String `tfsdk:"video_id"`
}

var _ basetypes.ObjectTypable = VideoHotSegmentsDataSourceSegmentsType{}

type VideoHotSegmentsDataSourceSegmentsType struct {
	basetypes.ObjectType
}

func (t VideoHotSegmentsDataSourceSegmentsType) Equal(o attr.Type) bool {
	other, ok := o.(VideoHotSegmentsDataSourceSegmentsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t VideoHotSegmentsDataSourceSegmentsType) String() string {
	return "SegmentsType"
}

func (t VideoHotSegmentsDataSourceSegmentsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	endSecondAttribute, ok := attributes["end_second"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_second is missing from object`)

		return nil, diags
	}

	endSecondVal, ok := endSecondAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_second expected to be basetypes.Int64Value, was: %T`, endSecondAttribute))
	}

	multiplierAttribute, ok := attributes["multiplier"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`multiplier is missing from object`)

		return nil, diags
	}

	multiplierVal, ok := multiplierAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`multiplier expected to be basetypes.Float64Value, was: %T`, multiplierAttribute))
	}

	startSecondAttribute, ok := attributes["start_second"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_second is missing from object`)

		return nil, diags
	}

	startSecondVal, ok := startSecondAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_second expected to be basetypes.Int64Value, was: %T`, startSecondAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return VideoHotSegmentsDataSourceSegmentsValue{
		EndSecond:   endSecondVal,
		Multiplier:  multiplierVal,
		StartSecond: startSecondVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewVideoHotSegmentsDataSourceSegmentsValueNull() VideoHotSegmentsDataSourceSegmentsValue {
	return VideoHotSegmentsDataSourceSegmentsValue{
		state: attr.ValueStateNull,
	}
}

func NewVideoHotSegmentsDataSourceSegmentsValueUnknown() VideoHotSegmentsDataSourceSegmentsValue {
	return VideoHotSegmentsDataSourceSegmentsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewVideoHotSegmentsDataSourceSegmentsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (VideoHotSegmentsDataSourceSegmentsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SegmentsValue Attribute Value",
				"While creating a SegmentsValue value, a missing attribute value was detected. "+
					"A SegmentsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SegmentsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SegmentsValue Attribute Type",
				"While creating a SegmentsValue value, an invalid attribute value was detected. "+
					"A SegmentsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SegmentsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SegmentsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SegmentsValue Attribute Value",
				"While creating a SegmentsValue value, an extra attribute value was detected. "+
					"A SegmentsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SegmentsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewVideoHotSegmentsDataSourceSegmentsValueUnknown(), diags
	}

	endSecondAttribute, ok := attributes["end_second"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_second is missing from object`)

		return NewVideoHotSegmentsDataSourceSegmentsValueUnknown(), diags
	}

	endSecondVal, ok := endSecondAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_second expected to be basetypes.Int64Value, was: %T`, endSecondAttribute))
	}

	multiplierAttribute, ok := attributes["multiplier"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`multiplier is missing from object`)

		return NewVideoHotSegmentsDataSourceSegmentsValueUnknown(), diags
	}

	multiplierVal, ok := multiplierAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`multiplier expected to be basetypes.Float64Value, was: %T`, multiplierAttribute))
	}

	startSecondAttribute, ok := attributes["start_second"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_second is missing from object`)

		return NewVideoHotSegmentsDataSourceSegmentsValueUnknown(), diags
	}

	startSecondVal, ok := startSecondAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_second expected to be basetypes.Int64Value, was: %T`, startSecondAttribute))
	}

	if diags.HasError() {
		return NewVideoHotSegmentsDataSourceSegmentsValueUnknown(), diags
	}

	return VideoHotSegmentsDataSourceSegmentsValue{
		EndSecond:   endSecondVal,
		Multiplier:  multiplierVal,
		StartSecond: startSecondVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewVideoHotSegmentsDataSourceSegmentsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) VideoHotSegmentsDataSourceSegmentsValue {
	object, diags := NewVideoHotSegmentsDataSourceSegmentsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSegmentsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t VideoHotSegmentsDataSourceSegmentsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewVideoHotSegmentsDataSourceSegmentsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewVideoHotSegmentsDataSourceSegmentsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewVideoHotSegmentsDataSourceSegmentsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewVideoHotSegmentsDataSourceSegmentsValueMust(VideoHotSegmentsDataSourceSegmentsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t VideoHotSegmentsDataSourceSegmentsType) ValueType(ctx context.Context) attr.Value {
	return VideoHotSegmentsDataSourceSegmentsValue{}
}

var _ basetypes.ObjectValuable = VideoHotSegmentsDataSourceSegmentsValue{}

type VideoHotSegmentsDataSourceSegmentsValue struct {
	EndSecond   basetypes.Int64Value   `tfsdk:"end_second"`
	Multiplier  basetypes.Float64Value `tfsdk:"multiplier"`
	StartSecond basetypes.Int64Value   `tfsdk:"start_second"`
	state       attr.ValueState
}

func (v VideoHotSegmentsDataSourceSegmentsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["end_second"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["multiplier"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["start_second"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.EndSecond.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_second"] = val

		val, err = v.Multiplier.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["multiplier"] = val

		val, err = v.StartSecond.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_second"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v VideoHotSegmentsDataSourceSegmentsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v VideoHotSegmentsDataSourceSegmentsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v VideoHotSegmentsDataSourceSegmentsValue) String() string {
	return "SegmentsValue"
}

func (v VideoHotSegmentsDataSourceSegmentsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"end_second":   basetypes.Int64Type{},
		"multiplier":   basetypes.Float64Type{},
		"start_second": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"end_second":   v.EndSecond,
			"multiplier":   v.Multiplier,
			"start_second": v.StartSecond,
		})

	return objVal, diags
}

func (v VideoHotSegmentsDataSourceSegmentsValue) Equal(o attr.Value) bool {
	other, ok := o.(VideoHotSegmentsDataSourceSegmentsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.EndSecond.Equal(other.EndSecond) {
		return false
	}

	if !v.Multiplier.Equal(other.Multiplier) {
		return false
	}

	if !v.StartSecond.Equal(other.StartSecond) {
		return false
	}

	return true
}

func (v VideoHotSegmentsDataSourceSegmentsValue) Type(ctx context.Context) attr.Type {
	return VideoHotSegmentsDataSourceSegmentsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v VideoHotSegmentsDataSourceSegmentsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"end_second":   basetypes.Int64Type{},
		"multiplier":   basetypes.Float64Type{},
		"start_second": basetypes.Int64Type{},
	}
}
